"use client";

import Link from "next/link";
import { Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ArrowRight, BarChart3, Building2, CreditCard, Download, FileSpreadsheet, Lightbulb, ReceiptText, Scale, Search, TrendingUp, Wallet } from "lucide-react";

type Dept = { name: string; revenue: number | null; cost: number | null; profit: number | null; margin: number | null; state: "ok" | "incomplete" | "untracked"; href: string };
type Trend = { label: string; revenue: number; expenses: number };
type Branch = { name: string; revenue: number; cost: number; profit: number };
export interface ExecutiveReportsProps {
  filters: { range: string; branch: string; shop: string; branches: { id: string; name: string }[]; shops: { id: string; name: string; branch_id: string | null }[] };
  kpis: { revenue: number; directCost: number; otherExpenses: number; net: number; receivables: number | null; payables: number | null };
  trend: Trend[]; branchRows: Branch[]; departments: Dept[]; insights: string[];
}

const COLORS = ["#1f8a4c", "#f2b134", "#2f80ed", "#f47721", "#7559c9", "#9aa69c"];
const tooltipStyle = { borderRadius: 10, border: "1px solid #e2e8e3", fontSize: 12 };
const money = (n: number | null) => n == null ? "—" : `Rs ${Math.round(n).toLocaleString()}`;
const shortMoney = (n: number) => Math.abs(n) >= 1_000_000 ? `${(n / 1_000_000).toFixed(1)}M` : Math.abs(n) >= 1_000 ? `${Math.round(n / 1_000)}K` : `${Math.round(n)}`;

function exportCsv(rows: Dept[]) {
  const data = [["Department", "Revenue", "Cost", "Profit / Loss", "Margin %", "Status"], ...rows.map((r) => [r.name, r.revenue ?? "", r.cost ?? "", r.profit ?? "", r.margin ?? "", r.state])];
  const csv = data.map((row) => row.map((v) => `"${String(v).replace(/"/g, '""')}"`).join(",")).join("\n");
  const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" }));
  const anchor = document.createElement("a"); anchor.href = url; anchor.download = `agribridge-report-${new Date().toISOString().slice(0, 10)}.csv`; anchor.click(); URL.revokeObjectURL(url);
}

function Kpi({ label, value, icon: Icon, className }: { label: string; value: number | null; icon: typeof TrendingUp; className: string }) {
  return <div className={`rounded-xl border border-surface-200 p-3 shadow-card dark:border-surface-800 ${className}`}><div className="flex items-start justify-between"><div><p className="text-[11px] font-semibold text-surface-600">{label}</p><p className="mt-1 text-xl font-bold tracking-tight text-surface-900 dark:text-white">{money(value)}</p><p className="mt-0.5 text-[10px] text-surface-400">Verified records</p></div><span className="rounded-xl bg-white/75 p-2 shadow-sm dark:bg-surface-800"><Icon className="h-5 w-5" /></span></div></div>;
}

export function ExecutiveReportsDashboard({ filters, kpis, trend, branchRows, departments, insights }: ExecutiveReportsProps) {
  const contribution = departments.filter((d) => (d.revenue ?? 0) > 0).map((d) => ({ name: d.name, value: d.revenue! }));
  const status = [
    { name: "Profitable", value: departments.filter((d) => d.profit != null && d.profit > 0).length, color: "#1f8a4c" },
    { name: "Loss", value: departments.filter((d) => d.profit != null && d.profit < 0).length, color: "#d64545" },
    { name: "Incomplete", value: departments.filter((d) => d.state !== "ok").length, color: "#f2a93b" },
  ];
  const shops = filters.branch ? filters.shops.filter((s) => s.branch_id === filters.branch) : filters.shops;
  const pieData = contribution.length ? contribution : [{ name: "No recorded revenue", value: 1 }];

  return <div className="mx-auto w-full max-w-[1800px] space-y-3 2xl:h-[calc(100vh-7rem)] 2xl:overflow-hidden">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="font-display text-2xl font-bold tracking-tight text-surface-900 dark:text-white">Reports &amp; Analytics</h1><p className="mt-0.5 text-sm text-surface-500">Real business performance, trends and decisions</p></div><div className="flex gap-2"><button onClick={() => window.print()} className="inline-flex items-center gap-2 rounded-lg bg-brand-700 px-3 py-2 text-xs font-semibold text-white hover:bg-brand-800"><Download className="h-4 w-4" />Export PDF</button><button onClick={() => exportCsv(departments)} className="inline-flex items-center gap-2 rounded-lg border border-brand-300 bg-white px-3 py-2 text-xs font-semibold text-brand-700 hover:bg-brand-25 dark:bg-surface-900"><FileSpreadsheet className="h-4 w-4" />Export Excel</button></div></div>

    <form className="grid grid-cols-2 gap-2 lg:grid-cols-5"><select name="range" defaultValue={filters.range} className="rounded-lg border border-surface-200 bg-white px-3 py-2 text-xs font-semibold dark:border-surface-700 dark:bg-surface-900"><option value="month">This Month</option><option value="week">This Week</option><option value="today">Today</option><option value="quarter">This Quarter</option></select><select name="department" defaultValue="" className="rounded-lg border border-surface-200 bg-white px-3 py-2 text-xs font-semibold dark:border-surface-700 dark:bg-surface-900"><option value="">All Departments</option>{departments.map((d) => <option key={d.name}>{d.name}</option>)}</select><select name="branch" defaultValue={filters.branch} className="rounded-lg border border-surface-200 bg-white px-3 py-2 text-xs font-semibold dark:border-surface-700 dark:bg-surface-900"><option value="">All Branches</option>{filters.branches.map((b) => <option key={b.id} value={b.id}>{b.name}</option>)}</select><select name="shop" defaultValue={filters.shop} className="rounded-lg border border-surface-200 bg-white px-3 py-2 text-xs font-semibold dark:border-surface-700 dark:bg-surface-900"><option value="">All Shops</option>{shops.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</select><button className="rounded-lg border border-surface-200 bg-white px-3 py-2 text-xs font-semibold text-brand-700 hover:bg-brand-25 dark:bg-surface-900">Apply Filters</button></form>

    <div className="grid grid-cols-2 gap-2 lg:grid-cols-3 2xl:grid-cols-6"><Kpi label="Total Revenue" value={kpis.revenue} icon={BarChart3} className="bg-emerald-50/70 text-emerald-700" /><Kpi label="Direct Cost" value={kpis.directCost} icon={ReceiptText} className="bg-rose-50/70 text-rose-600" /><Kpi label="Other Expenses" value={kpis.otherExpenses} icon={FileSpreadsheet} className="bg-blue-50/70 text-blue-600" /><Kpi label="Net Profit / Loss" value={kpis.net} icon={Scale} className={kpis.net < 0 ? "bg-rose-50/70 text-rose-600" : "bg-emerald-50/70 text-emerald-700"} /><Kpi label="Receivables" value={kpis.receivables} icon={Wallet} className="bg-amber-50/70 text-amber-700" /><Kpi label="Payables" value={kpis.payables} icon={CreditCard} className="bg-rose-50/70 text-rose-600" /></div>

    <div className="grid gap-3 xl:grid-cols-[minmax(0,2fr)_minmax(300px,1fr)]"><section className="rounded-xl border border-surface-200 bg-white p-3 shadow-card dark:border-surface-800 dark:bg-surface-900"><div className="mb-1 flex justify-between"><h2 className="flex items-center gap-2 text-sm font-bold"><TrendingUp className="h-4 w-4 text-brand-600" />Revenue &amp; Expense Trend</h2><span className="rounded-md bg-brand-700 px-2 py-1 text-[10px] font-semibold text-white">Monthly</span></div><div className="h-[190px] 2xl:h-[205px]"><ResponsiveContainer><LineChart data={trend} margin={{ left: 0, right: 10, top: 8 }}><CartesianGrid strokeDasharray="3 3" stroke="#e2e8e3" /><XAxis dataKey="label" tick={{ fontSize: 10 }} /><YAxis width={44} tickFormatter={shortMoney} tick={{ fontSize: 9 }} /><Tooltip formatter={(v) => money(Number(v))} contentStyle={tooltipStyle} /><Line type="monotone" dataKey="revenue" name="Revenue" stroke="#1f8a4c" strokeWidth={2.5} dot={{ r: 3 }} /><Line type="monotone" dataKey="expenses" name="Expenses" stroke="#2f80ed" strokeWidth={2.5} dot={{ r: 3 }} /></LineChart></ResponsiveContainer></div></section><section className="rounded-xl border border-surface-200 bg-white p-3 shadow-card dark:border-surface-800 dark:bg-surface-900"><h2 className="flex items-center gap-2 text-sm font-bold"><BarChart3 className="h-4 w-4 text-brand-600" />Department Contribution</h2><div className="grid h-[190px] grid-cols-[1.15fr_1fr] items-center 2xl:h-[205px]"><ResponsiveContainer><PieChart><Pie data={pieData} dataKey="value" nameKey="name" innerRadius="52%" outerRadius="80%">{pieData.map((_, i) => <Cell key={i} fill={contribution.length ? COLORS[i % COLORS.length] : "#e2e8e3"} />)}</Pie><Tooltip formatter={(v) => contribution.length ? money(Number(v)) : "—"} contentStyle={tooltipStyle} /></PieChart></ResponsiveContainer><div className="space-y-2">{(contribution.length ? contribution : [{ name: "No recorded revenue", value: 0 }]).slice(0, 6).map((d, i) => <div key={d.name} className="flex items-center justify-between gap-2 text-[10px]"><span className="flex min-w-0 items-center gap-2"><i className="h-2.5 w-2.5 shrink-0 rounded-full" style={{ background: contribution.length ? COLORS[i % COLORS.length] : "#cbd4cc" }} /><span className="truncate">{d.name}</span></span><strong>{contribution.length && kpis.revenue > 0 ? `${Math.round(d.value / kpis.revenue * 100)}%` : "—"}</strong></div>)}</div></div></section></div>

    <div className="grid gap-3 xl:grid-cols-[1.35fr_.8fr_1.05fr]"><section className="rounded-xl border border-surface-200 bg-white p-3 shadow-card dark:border-surface-800 dark:bg-surface-900"><h2 className="flex items-center gap-2 text-sm font-bold"><Building2 className="h-4 w-4 text-brand-600" />Branch Performance</h2><div className="h-[150px]"><ResponsiveContainer><BarChart data={branchRows.slice(0, 6)} margin={{ left: 0, right: 6, top: 8 }}><CartesianGrid strokeDasharray="3 3" stroke="#e2e8e3" /><XAxis dataKey="name" tick={{ fontSize: 8 }} /><YAxis width={40} tickFormatter={shortMoney} tick={{ fontSize: 8 }} /><Tooltip formatter={(v) => money(Number(v))} contentStyle={tooltipStyle} /><Bar dataKey="revenue" fill="#1f8a4c" radius={[3, 3, 0, 0]} /><Bar dataKey="cost" fill="#2f80ed" radius={[3, 3, 0, 0]} /><Bar dataKey="profit" fill="#f2a93b" radius={[3, 3, 0, 0]} /></BarChart></ResponsiveContainer></div></section><section className="rounded-xl border border-surface-200 bg-white p-3 shadow-card dark:border-surface-800 dark:bg-surface-900"><h2 className="text-sm font-bold">Profit &amp; Loss Status</h2><div className="grid h-[150px] grid-cols-[1.15fr_1fr] items-center"><ResponsiveContainer><PieChart><Pie data={status.some((s) => s.value) ? status : [{ name: "No status", value: 1, color: "#e2e8e3" }]} dataKey="value" innerRadius="45%" outerRadius="74%">{(status.some((s) => s.value) ? status : [{ color: "#e2e8e3" }]).map((s, i) => <Cell key={i} fill={s.color} />)}</Pie></PieChart></ResponsiveContainer><div className="space-y-2">{status.map((s) => <div key={s.name} className="flex justify-between text-[10px]"><span><i className="mr-1.5 inline-block h-2.5 w-2.5 rounded-full" style={{ background: s.color }} />{s.name}</span><strong>{s.value}</strong></div>)}</div></div></section><section className="rounded-xl border border-surface-200 bg-white p-3 shadow-card dark:border-surface-800 dark:bg-surface-900"><div className="mb-2 flex justify-between"><h2 className="flex items-center gap-2 text-sm font-bold"><Lightbulb className="h-4 w-4 text-brand-600" />AI Management Insight</h2><Link href="/admin/bridge-ai" className="text-[10px] font-semibold text-brand-700">View all</Link></div><div className="space-y-2">{insights.slice(0, 3).map((line, i) => <div key={i} className={`rounded-lg border px-2.5 py-2 text-[10px] leading-relaxed ${i === 0 ? "border-emerald-100 bg-emerald-50/70" : i === 1 ? "border-amber-100 bg-amber-50/70" : "border-blue-100 bg-blue-50/70"}`}>{line.replace(/\*\*/g, "")}</div>)}{!insights.length && <p className="py-6 text-center text-xs text-surface-400">No verified insight available.</p>}</div></section></div>

    <section className="overflow-hidden rounded-xl border border-surface-200 bg-white shadow-card dark:border-surface-800 dark:bg-surface-900"><div className="flex items-center justify-between border-b border-surface-100 px-3 py-2 dark:border-surface-800"><h2 className="flex items-center gap-2 text-sm font-bold"><ReceiptText className="h-4 w-4 text-brand-600" />Detailed Report</h2><div className="flex items-center gap-2"><span className="hidden items-center gap-1.5 rounded-lg border border-surface-200 px-2 py-1 text-[10px] text-surface-400 sm:flex"><Search className="h-3 w-3" />Search reports...</span><Link href="/admin/master-dashboard" className="inline-flex items-center gap-1 rounded-lg border border-brand-300 px-2 py-1 text-[10px] font-semibold text-brand-700">View Full Report <ArrowRight className="h-3 w-3" /></Link></div></div><div className="overflow-x-auto"><table className="w-full text-[10px]"><thead className="bg-surface-50 text-surface-500 dark:bg-surface-800"><tr><th className="px-3 py-1.5 text-left">Department</th><th className="px-3 py-1.5 text-right">Revenue</th><th className="px-3 py-1.5 text-right">Cost</th><th className="px-3 py-1.5 text-right">Profit / Loss</th><th className="px-3 py-1.5 text-right">Margin</th><th className="px-3 py-1.5 text-center">Status</th></tr></thead><tbody>{departments.slice(0, 6).map((d) => <tr key={d.name} className="border-t border-surface-100 dark:border-surface-800"><td className="px-3 py-1.5 font-semibold"><Link href={d.href}>{d.name}</Link></td><td className="px-3 py-1.5 text-right">{money(d.revenue)}</td><td className="px-3 py-1.5 text-right">{money(d.cost)}</td><td className={`px-3 py-1.5 text-right font-semibold ${d.profit != null && d.profit < 0 ? "text-red-600" : "text-green-700"}`}>{money(d.profit)}</td><td className="px-3 py-1.5 text-right">{d.margin == null ? "—" : `${d.margin.toFixed(1)}%`}</td><td className="px-3 py-1.5 text-center"><span className={`rounded-full px-2 py-0.5 font-semibold ${d.state === "ok" ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{d.state === "ok" ? "Complete" : d.state === "incomplete" ? "Incomplete" : "Not tracked"}</span></td></tr>)}</tbody></table></div></section>
  </div>;
}
