import { redirect } from "next/navigation";
import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { loadNav, routeAllowed } from "@/lib/access/nav";
import { loadNeedsAttention, filterAttention } from "@/lib/access/needs-attention";
import { buildMyWork, loadFourthKpi, loadRecentActivity } from "@/lib/access/my-work";
import { departmentForRole } from "@/lib/departments";
import { getLanguageFromCookies } from "@/lib/i18n/get-language";
import { t } from "@/lib/i18n/translations";
import * as I from "lucide-react";

export const dynamic = "force-dynamic";

const toneClass: Record<string,string> = { red:"bg-red-50 text-red-600", amber:"bg-amber-50 text-amber-600", blue:"bg-blue-50 text-blue-600", gray:"bg-surface-50 text-surface-600" };
const deptIcon: Record<string, any> = { milk:I.Droplets, grain:I.Wheat, machinery:I.Wrench, sales:I.ShoppingCart, finance:I.Landmark, hr:I.Users };

export default async function MyWorkReferencePage(){
 const supabase=createClient(); const lang=getLanguageFromCookies("rm");
 const {data:{user}}=await supabase.auth.getUser(); if(!user) redirect("/login");
 const {data:me}=await supabase.from("profiles").select("full_name,role,branch_id").eq("id",user.id).maybeSingle(); if(!me) redirect("/login");
 const nav=await loadNav(user.id,me.role,lang); const allowed=nav.unrestricted?null:nav.allowedRoutes; const groups=nav.groups.filter(g=>g.items.length>0);
 const model=await buildMyWork(groups,allowed,me.role,lang); const attention=filterAttention(await loadNeedsAttention(),allowed);
 const [{data:branch},fourth,recent]=await Promise.all([me.branch_id?supabase.from("branches").select("name").eq("id",me.branch_id).maybeSingle():Promise.resolve({data:null}),loadFourthKpi(me.branch_id,allowed,lang),loadRecentActivity(me.branch_id,allowed)]);
 const can=(p:string)=>allowed===null||routeAllowed(allowed,p); const role=(me.role||"").split("_").map((x:string)=>x[0]?.toUpperCase()+x.slice(1)).join(" "); const dept=departmentForRole(me.role);
 const kpis=[{label:"Pending Approvals",value:attention.filter(x=>x.tone==="amber").length,icon:I.UserCheck,box:"bg-emerald-50 text-emerald-700"},{label:"My Open Tasks",value:attention.length,icon:I.ClipboardCheck,box:"bg-emerald-50 text-emerald-700"},{label:"Urgent Today",value:attention.filter(x=>x.tone==="red").length,icon:I.Clock3,box:"bg-red-50 text-red-600"},...(fourth?[{label:fourth.label,value:fourth.value,icon:I.Users,box:"bg-blue-50 text-blue-600"}]:[])];
 const quick=[can("/admin/kharche")&&["/admin/kharche","Paisa & Khata",I.WalletCards],can("/admin/farmers")&&["/admin/farmers","Add Farmer",I.UserPlus],can("/admin/agri-orders/new")&&["/admin/agri-orders/new","Create Order",I.ShoppingCart],can("/admin/load-bill")&&["/admin/load-bill","Receive Payment",I.Banknote]].filter(Boolean) as [string,string,any][];
 const now=new Intl.DateTimeFormat("en-GB",{timeZone:"Asia/Karachi",weekday:"short",day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit",hour12:true}).format(new Date());
 return <div className="mx-auto w-full max-w-[1500px] px-2 pb-6">
  <div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-[25px] font-bold tracking-tight text-surface-950">Good evening, {me.full_name} 👋</h1><p className="text-[12px] text-surface-500">{[role,dept?.label,branch?.name].filter(Boolean).join(" · ")}</p></div><div className="flex items-center gap-2 text-[12px] font-medium text-surface-600"><I.CalendarDays className="h-4 w-4"/>{now}</div></div>
  <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_280px]">
   <main className="min-w-0 space-y-4">
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{kpis.map(({label,value,icon:Icon,box})=><div key={label} className="flex min-h-[82px] items-center gap-3 rounded-2xl border border-surface-200 bg-white px-4 shadow-sm"><span className={`grid h-11 w-11 place-items-center rounded-xl ${box}`}><Icon className="h-5 w-5"/></span><div><p className="text-2xl font-bold leading-none">{value??"—"}</p><p className="mt-2 text-[12px] text-surface-500">{label}</p></div></div>)}</div>
    <div className="flex min-h-[58px] flex-wrap items-center justify-between gap-3 rounded-2xl border border-emerald-100 bg-emerald-50/70 px-5"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-full bg-emerald-500 text-white"><I.Check className="h-5 w-5"/></span><div><p className="text-sm font-semibold">{attention.some(x=>x.tone==="red")?"Important work needs your attention.":"No urgent work pending today."}</p><p className="text-[11px] text-surface-500">{attention.length?`${attention.length} item(s) need review.`:"You're up to date! Keep up the good work."}</p></div></div><div className="flex items-center gap-2 text-[11px] text-surface-500"><span>Recently Used:</span>{model.quick.slice(0,4).map((q:any)=><Link key={q.href} href={q.href} className="rounded-lg bg-white px-3 py-1.5 font-medium text-surface-700 shadow-sm">{q.label}</Link>)}</div></div>
    <div className="grid gap-4 lg:grid-cols-2">
     <section className="rounded-2xl border border-surface-200 bg-white p-4 shadow-sm"><div className="mb-3 flex items-center justify-between"><div><h2 className="flex items-center gap-2 text-sm font-bold"><I.Map className="h-4 w-4"/>Your Departments</h2><p className="mt-1 text-[11px] text-surface-500">Quick access to your daily work</p></div></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{model.departments.slice(0,6).map((d:any)=>{const Icon=deptIcon[d.key]||I.LayoutGrid;return <div key={d.key} className="flex min-h-[68px] items-center gap-3 rounded-xl border border-surface-200 px-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-emerald-50 text-emerald-700"><Icon className="h-4 w-4"/></span><span className="text-[12px] font-medium">{d.label}</span><I.ChevronRight className="ml-auto h-4 w-4 text-surface-300"/></div>})}</div></section>
     <section className="rounded-2xl border border-surface-200 bg-white p-4 shadow-sm"><div className="mb-3 flex items-center justify-between"><h2 className="flex items-center gap-2 text-sm font-bold"><I.ClipboardList className="h-4 w-4"/>Today's Tasks</h2><Link href="/admin/my-work?all=1" className="text-[11px] font-semibold text-emerald-700">View All</Link></div><div className="divide-y divide-surface-100">{attention.slice(0,4).map((a:any)=><Link href={a.href} key={a.key} className="flex items-center gap-3 py-3"><span className={`grid h-8 w-8 place-items-center rounded-lg ${toneClass[a.tone]||toneClass.gray}`}><I.CircleAlert className="h-4 w-4"/></span><div className="min-w-0"><p className="truncate text-[12px] font-semibold">{t(a.label,lang)}</p><p className="text-[11px] text-surface-400">{a.count} pending</p></div><I.ChevronRight className="ml-auto h-4 w-4 text-surface-300"/></Link>)}{attention.length===0&&<p className="py-8 text-center text-xs text-surface-400">No pending tasks.</p>}</div></section>
     <section className="rounded-2xl border border-surface-200 bg-white p-4 shadow-sm"><div className="mb-2 flex items-center justify-between"><h2 className="flex items-center gap-2 text-sm font-bold"><I.History className="h-4 w-4"/>Recent Activity</h2></div><div className="divide-y divide-surface-100">{recent.slice(0,4).map((a:any)=><div key={a.key} className="flex items-center gap-3 py-2.5"><span className="grid h-8 w-8 place-items-center rounded-lg bg-emerald-50 text-emerald-700"><I.ReceiptText className="h-4 w-4"/></span><div className="min-w-0"><p className="truncate text-[12px] font-semibold">{t(a.labelKey,lang)}</p><p className="truncate text-[11px] text-surface-400">{a.subtitle||""}</p></div>{a.amount!=null&&<span className="ml-auto text-[12px] font-bold">Rs {Number(a.amount).toLocaleString()}</span>}</div>)}{recent.length===0&&<p className="py-8 text-center text-xs text-surface-400">No recent activity.</p>}</div></section>
     <section className="rounded-2xl border border-surface-200 bg-white p-4 shadow-sm"><h2 className="mb-3 flex items-center gap-2 text-sm font-bold"><I.Zap className="h-4 w-4"/>Quick Actions</h2><div className="grid grid-cols-2 gap-2">{quick.map(([href,label,Icon],idx)=><Link key={href} href={href} className={`flex min-h-[52px] items-center gap-3 rounded-xl px-4 text-[12px] font-semibold ${idx===0?"bg-emerald-50 text-emerald-800":"bg-surface-50 text-surface-700"}`}><Icon className="h-5 w-5"/>{label}</Link>)}</div></section>
    </div>
   </main>
   <aside className="h-fit rounded-2xl border border-surface-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-surface-100 px-4 py-4"><h2 className="flex items-center gap-2 text-sm font-bold"><I.Bell className="h-4 w-4 text-emerald-700"/>Live Notifications</h2><Link href="/admin/notifications" className="text-[11px] font-semibold text-emerald-700">View All</Link></div><div className="p-2"><p className="px-3 py-3 text-[11px] leading-5 text-surface-500">Use the existing AgriBridge notification system here. This reference page intentionally does not create a second notification table or fake events.</p><Link href="/admin/notifications" className="mx-2 mb-2 flex items-center justify-center rounded-xl bg-emerald-50 px-3 py-2 text-[12px] font-semibold text-emerald-700">Open Notifications</Link></div></aside>
  </div>
 </div>;
}
