import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { Card, PageHeader } from "@/components/ui/layout-primitives";
import { saveReminderTemplate } from "@/actions/recovery";
export const dynamic="force-dynamic";
export default async function TemplatesPage(){
 const db=createClient() as any; const {data}=await db.from("reminder_templates").select("*").order("template_name");
 return <div className="space-y-4"><PageHeader title="Reminder Templates" description="WhatsApp, SMS aur Email ke approved message drafts."/><Link href="/admin/finance/recovery" className="text-sm underline">← Recovery Dashboard</Link><Card><form action={saveReminderTemplate} className="grid gap-3 md:grid-cols-4"><input required name="name" placeholder="Template name" className="rounded-lg border p-2"/><select name="language" className="rounded-lg border p-2"><option value="roman_urdu">Roman Urdu</option><option value="ur">Urdu</option><option value="en">English</option></select><select name="channel" className="rounded-lg border p-2"><option value="whatsapp">WhatsApp</option><option value="sms">SMS</option><option value="email">Email</option></select><select name="stage" className="rounded-lg border p-2"><option value="friendly">Friendly</option><option value="due_today">Due Today</option><option value="overdue">Overdue</option><option value="final">Final Follow-up</option></select><textarea required name="body" placeholder="Use {{party_name}}, {{outstanding_amount}}, {{due_date}}" className="min-h-24 rounded-lg border p-2 md:col-span-3"/><label className="flex items-center gap-2 text-sm"><input name="active" type="checkbox" defaultChecked/> Active</label><button className="rounded-lg bg-emerald-600 px-4 py-2 text-white md:col-span-4">Save Template</button></form></Card><div className="grid gap-3 lg:grid-cols-2">{(data||[]).map((t:any)=><Card key={t.id}><div className="flex justify-between"><h3 className="font-semibold">{t.template_name}</h3><span className="text-xs uppercase text-surface-500">{t.channel} · {t.language}</span></div><p className="mt-2 whitespace-pre-wrap text-sm text-surface-600">{t.message_body}</p><p className="mt-2 text-xs text-surface-400">Stage: {t.reminder_stage} · {t.is_active?"Active":"Inactive"}</p></Card>)}</div></div>;
}
