-- =====================================================================
-- AgriBridge — Migration 266: Har feature ki maloomat system ke andar
-- =====================================================================
-- Guided ERP (docs/GUIDED-ERP.md) ka qadam A.
--
-- Malik ka usool: koi feature "poora" nahi jab tak us ki help likhi na
-- ho. Ye table wo help hai: maqsad, kaun, kab, kaise, agla qadam,
-- ghaltiyan, video, FAQ, mutalliqa safhe. Har feature, har zaban ki
-- apni qatar. Safhe par "? Is Page Ko Samjhein" isi ko dikhata hai, aur
-- Work Coach (qadam C) ka har jawab isi se aayega -- AI ke apne ilm se
-- nahi.
--
-- Zaban na mile to Roman (rm) dikhaya jata hai -- khali panel se behtar.
-- =====================================================================

create table if not exists feature_help (
  feature_key text not null references features(key) on delete cascade,
  lang text not null default 'rm',
  purpose text not null,
  who_uses text,
  when_use text,
  how_steps text[] not null default '{}',
  next_step text,
  mistakes text[] not null default '{}',
  video_url text,
  faq jsonb not null default '[]'::jsonb,
  related text[] not null default '{}',
  updated_at timestamptz not null default now(),
  updated_by uuid references profiles(id),
  primary key (feature_key, lang),
  constraint chk_feature_help_lang check (lang in ('rm', 'en', 'ur'))
);

comment on table feature_help is
  'Har feature ki tasdeeq-shuda maloomat: insaan bhi parhe, AI bhi (266). Guided ERP ki jaR.';

alter table feature_help enable row level security;
drop policy if exists feature_help_read on feature_help;
create policy feature_help_read on feature_help
  for select to authenticated using (public.fn_is_any_staff());
drop policy if exists feature_help_write on feature_help;
create policy feature_help_write on feature_help
  for all to authenticated
  using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_active
                 and p.role::text in ('owner','super_admin','admin')))
  with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_active
                 and p.role::text in ('owner','super_admin','admin')));

insert into feature_help (feature_key, lang, purpose, who_uses, when_use, how_steps, next_step, mistakes, faq, related)
select v.* from (values
($h$products.setup$h$, $h$rm$h$, $h$Adhoore products ko bikri ke liye tayyar karna: rate, barcode, tasveer, miyaad, manzoori — sab ek jagah.$h$, $h$Owner, Admin, Warehouse$h$, $h$Naya maal aane ke baad; POS par koi cheez na mile; sheet ya bill se products charhne ke baad.$h$, array[$h$Upar ke khane dekhein: kis cheez ki kitni baqi hai (rate, barcode, tasveer, miyaad, manzoori).$h$,$h$Khana dabayein to fehrist usi par chhant jati hai.$h$,$h$Rate ke khane mein rate likhein, barcode scan karein, tasveer ke liye edit par jayein.$h$,$h$Owner/Admin manzoori ka nishan lagayein.$h$,$h$Neeche 'Mehfooz karein' dabayein — khali khana kuch nahi badalta.$h$]::text[], $h$Jab sale rate, aur jo kuch zaroori hai, poora ho jaye to product Sale Ready hai aur POS par aa jata hai.$h$, array[$h$Sale rate mein 0 likhna — 0 ka matlab muft; khali chhoRein.$h$,$h$Ek naam ke do products — naam mein pack size lagayein (Sufi 5 Ltr, Sufi 1 Ltr).$h$,$h$Barcode haath se ghalat likhna — scanner se lein, ya 'apna barcode bana dein'.$h$]::text[], $h$[{"q": "Barcode nahi hai to?", "a": "'Ya apna barcode bana dein' par nishan lagayein — system 200 se shuru hone wala EAN-13 deta hai, Barcode Label se chhaap lein."}, {"q": "Product POS par kyun nahi aa raha?", "a": "Sale rate baqi hai. Yahan rate bharein, foran aa jayega."}]$h$::jsonb, array[$h$products$h$,$h$products.labels$h$,$h$products.rates_baqi$h$,$h$pos$h$]::text[]),
($h$products.setup$h$, $h$en$h$, $h$Get incomplete products ready for sale: rate, barcode, photo, expiry, approval — in one place.$h$, $h$Owner, Admin, Warehouse$h$, $h$After new stock arrives; when an item is missing at the POS; after a sheet or bill import.$h$, array[$h$Read the tiles at the top: how many lack a rate, barcode, photo, expiry, approval.$h$,$h$Click a tile to filter the list.$h$,$h$Type rates, scan barcodes; use Edit for photos.$h$,$h$Owner/Admin tick approval.$h$,$h$Press Save — a blank field changes nothing.$h$]::text[], $h$Once the sale rate and required fields are complete the product is Sale Ready and appears on the POS.$h$, array[$h$Typing 0 as a sale rate — 0 means free; leave it blank.$h$,$h$Two products with the same name — add the pack size.$h$,$h$Typing a barcode by hand — scan it, or make an internal one.$h$]::text[], $h$[{"q": "No barcode on the pack?", "a": "Tick 'make an internal barcode' — the system issues a 200… EAN-13; print it from Barcode Labels."}]$h$::jsonb, array[$h$products$h$,$h$products.labels$h$,$h$products.rates_baqi$h$,$h$pos$h$]::text[]),
($h$products$h$, $h$rm$h$, $h$Sab products ki fehrist: naam, qism, rate, halat. Yahin se naya product, import aur export.$h$, $h$Owner, Admin, Warehouse, Sales$h$, $h$Product dhoondna ho, rate dekhna ho, naya product banana ho.$h$, array[$h$Upar qism ke tab se chhantein (Fertilizer, Grocery...).$h$,$h$Naam likh kar dhoondein.$h$,$h$Daayen: Add Product, Import (sheet se), Export (catalogue).$h$,$h$Edit par rate, tasveer, pack size badlein.$h$]::text[], $h$Product mein kuch adhoora ho to Product Setup par nishan aata hai; poora ho to POS par bikta hai.$h$, array[$h$Ek hi cheez do naam se banana.$h$,$h$Purchase Price khali chhoRna — 'baqi' likha aata hai, munafa ghalat dikhta hai.$h$]::text[], $h$[{"q": "Bahut se products ek sath?", "a": "Import dabayein, CSV sheet charhayein."}]$h$::jsonb, array[$h$products.setup$h$,$h$products.import$h$,$h$product-masters$h$]::text[]),
($h$products$h$, $h$en$h$, $h$Master list of products with name, category, rates and status. Add, import and export from here.$h$, $h$Owner, Admin, Warehouse, Sales$h$, $h$To find a product, check a rate, or add a new one.$h$, array[$h$Filter by category tabs.$h$,$h$Search by name.$h$,$h$Top right: Add Product, Import, Export.$h$,$h$Edit to change rates, photo, pack size.$h$]::text[], $h$Anything missing shows up in Product Setup; complete products sell at the POS.$h$, array[$h$Creating the same item twice under different names.$h$,$h$Leaving purchase price empty — profit looks wrong.$h$]::text[], $h$[]$h$::jsonb, array[$h$products.setup$h$,$h$products.import$h$,$h$product-masters$h$]::text[]),
($h$products.intake$h$, $h$rm$h$, $h$Naya maal godam mein lena: dabbe ki tasveer se AI naam, MRP, tareekh parhta hai; aap jaanch kar manzoor karte hain.$h$, $h$Owner, Admin, Warehouse$h$, $h$Aisa maal aaye jo products mein pehle se nahi.$h$, array[$h$Naya chakkar kholein, godam chunein.$h$,$h$Har cheez ki tasveer lein (ya barcode scan karein).$h$,$h$AI jo parhe use dekhein, sale rate likhein.$h$,$h$Sab qatarein tayyar hon to 'Manzoor karein' — products bante hain aur stock charhta hai.$h$]::text[], $h$Manzoori ke baad product ka batch banta hai (miyaad ke sath). Rate baqi ho to Product Setup par nazar aayega.$h$, array[$h$AI ka parha hua bina dekhe manzoor karna — AI adad ghalat parh sakta hai.$h$,$h$Supplier se aaya maal yahan se charhana — us ke liye Purchase banao, warna supplier ka dena nahi banta.$h$]::text[], $h$[{"q": "Ye purchase se kaise alag hai?", "a": "Maal Andar sirf shuru ka ya bina bill ka maal hai. Supplier ka bill ho to Bill se Trade Rate → Purchase banayein."}]$h$::jsonb, array[$h$products.setup$h$,$h$products.bill_rates$h$,$h$purchases$h$]::text[]),
($h$products.intake$h$, $h$en$h$, $h$Bring new goods into the warehouse: AI reads the pack photo, you check and approve.$h$, $h$Owner, Admin, Warehouse$h$, $h$When goods arrive that are not yet products.$h$, array[$h$Open a batch, choose the warehouse.$h$,$h$Photograph each item or scan its barcode.$h$,$h$Check what AI read, type the sale rate.$h$,$h$Approve — products are created and stock comes in.$h$]::text[], $h$A batch with expiry is created. Missing rates show in Product Setup.$h$, array[$h$Approving without checking AI's numbers.$h$,$h$Using this for supplier goods — make a Purchase instead, or the supplier's payable is never recorded.$h$]::text[], $h$[]$h$::jsonb, array[$h$products.setup$h$,$h$products.bill_rates$h$,$h$purchases$h$]::text[]),
($h$products.bill_rates$h$, $h$rm$h$, $h$Supplier ke bill (photo, PDF ya sheet) se har qatar ka trade rate parh kar products par charhana, aur usi bill se Purchase banana.$h$, $h$Owner, Admin, Warehouse$h$, $h$Supplier ka bill aaye.$h$, array[$h$Bill ki tasveer/PDF charhayein ya sheet.$h$,$h$AI qatarein parhta hai; har qatar par product milata hai — 'andaza NN%' wali qatar khol kar Save dabayein.$h$,$h$Rate theek hon to 'Rate charhayein'.$h$,$h$'Purchase banayein' — purchase manzoori ke liye jati hai.$h$]::text[], $h$Purchase manzoor → Receiving par maal ginein → stock aur supplier ka dena charhta hai.$h$, array[$h$Andaze wala milaan bina dekhe chhoR dena — us par rate nahi charhta jab tak Save na dabayein.$h$,$h$Ek bill se do dafa purchase banana — system rokta hai.$h$]::text[], $h$[{"q": "Rate column dhundla hai?", "a": "AI wo qatar khali chhoRta hai, andaza nahi lagata. Aap haath se likhein."}]$h$::jsonb, array[$h$purchases$h$,$h$products.setup$h$,$h$suppliers$h$]::text[]),
($h$products.bill_rates$h$, $h$en$h$, $h$Read each line's trade rate from a supplier bill (photo, PDF or sheet), apply it to products, and create the Purchase from the same bill.$h$, $h$Owner, Admin, Warehouse$h$, $h$When a supplier bill arrives.$h$, array[$h$Upload the bill or sheet.$h$,$h$AI reads the lines and matches products — open any 'guessed NN%' line and press Save.$h$,$h$Apply rates.$h$,$h$Create Purchase — it goes for approval.$h$]::text[], $h$Approve → count goods in Receiving → stock and supplier payable update.$h$, array[$h$Ignoring guessed matches — their rate is not applied until you Save.$h$]::text[], $h$[]$h$::jsonb, array[$h$purchases$h$,$h$products.setup$h$,$h$suppliers$h$]::text[]),
($h$purchases$h$, $h$rm$h$, $h$Supplier se kharid: purchase banana, manzoor karna, aur maal aane par ginna (kitna theek, kitna toota, kitna kam).$h$, $h$Owner, Admin, Warehouse, Purchase staff$h$, $h$Supplier se maal mangwana ho ya aa gaya ho.$h$, array[$h$Daayen form se purchase banayein (ya Bill se Trade Rate se).$h$,$h$Manzoori baqi ho to 'Jaanch' — Owner/Admin manzoor / wapas / radd.$h$,$h$Maal aane par 'Maal Aa Gaya': har line par theek aaya, toota; kam khud nikalta hai; tasveer lagayein.$h$,$h$Toota ya kam ho to note zaroori.$h$]::text[], $h$Receive hote hi stock charhta hai aur supplier ka dena utne ka banta hai jitna theek aaya. Bill aur Dena par dikhta hai.$h$, array[$h$Manzoori se pehle receive ki koshish — database rokta hai.$h$,$h$Toote hue ko bhi 'theek aaya' likhna — phir us ka paisa supplier ko jata hai.$h$]::text[], $h$[{"q": "Adaigi kahan likhein?", "a": "Purchase banate waqt 'abhi diya' likhein, ya baad mein Suppliers → adaigi. Dena supplier ke kul se banta hai."}]$h$::jsonb, array[$h$products.bill_rates$h$,$h$purchases.bills$h$,$h$inventory.receiving$h$,$h$suppliers$h$]::text[]),
($h$purchases$h$, $h$en$h$, $h$Buying from suppliers: create, approve, and count goods in (OK / damaged / short).$h$, $h$Owner, Admin, Warehouse, Purchase staff$h$, $h$Ordering from a supplier or when goods arrive.$h$, array[$h$Create a purchase (or from a bill).$h$,$h$'Review' — Owner/Admin approve / send back / reject.$h$,$h$On arrival 'Goods Received': per line OK and damaged; short is computed; add a photo.$h$,$h$A note is required when anything is short or damaged.$h$]::text[], $h$Stock comes in and the supplier is owed only for what arrived OK.$h$, array[$h$Receiving before approval — blocked.$h$,$h$Counting damaged units as OK.$h$]::text[], $h$[]$h$::jsonb, array[$h$products.bill_rates$h$,$h$purchases.bills$h$,$h$inventory.receiving$h$,$h$suppliers$h$]::text[]),
($h$purchases.bills$h$, $h$rm$h$, $h$Har supplier ko kitna dena hai: kharida, ada kiya, baqi — aur agle 7 din mein kya due hai.$h$, $h$Owner, Admin, Finance$h$, $h$Supplier ko paisa bhejne se pehle; hafte ki adaigi ki tarteeb ke liye.$h$, array[$h$Upar 'agle 7 din' dekhein.$h$,$h$Har supplier ki qatar: kharida / ada / baqi / raaste mein.$h$,$h$'Kholein' se statement.$h$]::text[], $h$Adaigi Suppliers ke safhe se likhein — dena khud dobara ban jata hai.$h$, array[$h$Sirf 'baqi' dekh kar faisla — teenon adad sath dekhein.$h$,$h$Lal 'farq' ka paighaam nazar andaaz karna — matlab likha hua adad asal hisaab se hat gaya hai.$h$]::text[], $h$[]$h$::jsonb, array[$h$purchases$h$,$h$suppliers$h$]::text[]),
($h$purchases.bills$h$, $h$en$h$, $h$What each supplier is owed: bought, paid, balance — and what falls due in the next 7 days.$h$, $h$Owner, Admin, Finance$h$, $h$Before paying a supplier; weekly payment planning.$h$, array[$h$Check 'due in 7 days'.$h$,$h$Per supplier: bought / paid / balance / in transit.$h$,$h$Open the statement.$h$]::text[], $h$Record payments from Suppliers — the balance recomputes itself.$h$, array[$h$Ignoring a red mismatch warning.$h$]::text[], $h$[]$h$::jsonb, array[$h$purchases$h$,$h$suppliers$h$]::text[]),
($h$inventory$h$, $h$rm$h$, $h$Abhi kis godam mein kya para hai: tadad, qeemat, kam stock, qareeb miyaad.$h$, $h$Owner, Admin, Warehouse, Shop staff$h$, $h$Kisi cheez ka stock dekhna ho; kam maal ka alert; miyaad dekhni ho.$h$, array[$h$Qatar par product ka naam dabayein — us ka card: har godam mein para hua, rakha hua, khula, batch, miyaad, harkatein.$h$,$h$Theek karein (ginti ka farq) ya Bhejein (doosre godam).$h$]::text[], $h$Ginti yahan haath se nahi badalti — har tabdeeli ek harkat hai jo Stock Ledger mein dikhti hai.$h$, array[$h$Adjust se maal 'daalna' jo supplier se aaya — us ke liye Purchase.$h$,$h$Miyaad guzri cheez ko stock mein rehne dena.$h$]::text[], $h$[{"q": "'Rakha hua' kya hai?", "a": "Manzoor shuda shop order jo abhi bheja nahi. Wo maal bech dena order torta hai."}]$h$::jsonb, array[$h$stock-ledger$h$,$h$stock-transfers$h$,$h$products.setup$h$]::text[]),
($h$inventory$h$, $h$en$h$, $h$What is in each warehouse right now: quantity, value, low stock, near expiry.$h$, $h$Owner, Admin, Warehouse, Shop staff$h$, $h$Checking stock, low-stock alerts, expiry.$h$, array[$h$Click a product name for its card: on hand, reserved, available, batches, movements.$h$,$h$Adjust (count difference) or Transfer.$h$]::text[], $h$Quantities never change by hand — every change is a movement in the Stock Ledger.$h$, array[$h$Using Adjust for supplier goods — make a Purchase.$h$]::text[], $h$[]$h$::jsonb, array[$h$stock-ledger$h$,$h$stock-transfers$h$,$h$products.setup$h$]::text[]),
($h$stock-ledger$h$, $h$rm$h$, $h$Maal kab, kahan se, kis wajah se barha ya ghata: +50 kharid, −10 shop ko, −2 toota, +1 wapas.$h$, $h$Owner, Admin, Warehouse, Finance$h$, $h$Ginti mein farq aaye; 'ye maal kahan gaya' ka sawal ho.$h$, array[$h$Product ya godam se chhantein.$h$,$h$Har qatar ka hawala dekhein (purchase, order, return, adjust).$h$]::text[], $h$Stock = abhi kitna; Ledger = kaise bana. Dono ek hi harkaton se.$h$, array[$h$Ledger ko chhoR kar sirf stock ka adad theek karna.$h$]::text[], $h$[]$h$::jsonb, array[$h$inventory$h$,$h$stock-count$h$]::text[]),
($h$stock-ledger$h$, $h$en$h$, $h$When, from where and why stock went up or down.$h$, $h$Owner, Admin, Warehouse, Finance$h$, $h$When a count differs; to trace goods.$h$, array[$h$Filter by product or warehouse.$h$,$h$Read each row's reference.$h$]::text[], $h$Stock is the balance; the ledger is how it got there.$h$, array[]::text[], $h$[]$h$::jsonb, array[$h$inventory$h$,$h$stock-count$h$]::text[]),
($h$stock-transfers$h$, $h$rm$h$, $h$Ek godam ya shop se doosre ko maal bhejna.$h$, $h$Owner, Admin, Warehouse$h$, $h$Shop ko maal chahiye ya godam badalna ho.$h$, array[$h$Kahan se, kahan ko, kaun si cheez, kitni.$h$,$h$Bhejne par bhejne wale ka stock kam; lene wale ka tab barhta hai jab wo receive kare.$h$]::text[], $h$Raaste ka maal kisi ke stock mein nahi ginta — Receiving par aata hai.$h$, array[$h$Receive kiye baghair lene wali jagah par bechna — wahan stock abhi nahi hai.$h$]::text[], $h$[]$h$::jsonb, array[$h$inventory$h$,$h$inventory.receiving$h$]::text[]),
($h$stock-transfers$h$, $h$en$h$, $h$Move stock between warehouses and shops.$h$, $h$Owner, Admin, Warehouse$h$, $h$A shop needs goods or a warehouse changes.$h$, array[$h$From, to, item, quantity.$h$,$h$Sender's stock drops now; receiver's rises on receive.$h$]::text[], $h$Goods in transit belong to nobody's stock until received.$h$, array[$h$Selling at the destination before receiving.$h$]::text[], $h$[]$h$::jsonb, array[$h$inventory$h$,$h$inventory.receiving$h$]::text[]),
($h$agri-returns$h$, $h$rm$h$, $h$Shop se wapas aaya maal: shop banati hai, HQ receive kar ke manzoor karta hai.$h$, $h$Shop staff, Warehouse, Admin$h$, $h$Shop ko maal wapas bhejna ho (zyada, toota, miyaad).$h$, array[$h$Shop return banaye.$h$,$h$HQ receive kare — tab shop ka stock kam, HQ ka barhe, aur shop ke khate se qeemat kam.$h$]::text[], $h$Receive tak kuch nahi hilta — kaghaz par bheja aur asal mein pahuncha alag rehte hain.$h$, array[$h$Receive kiye baghair khate ko theek samajh lena.$h$]::text[], $h$[]$h$::jsonb, array[$h$inventory$h$,$h$stock-ledger$h$]::text[]),
($h$agri-returns$h$, $h$en$h$, $h$Goods coming back from a shop: shop creates, HQ receives and approves.$h$, $h$Shop staff, Warehouse, Admin$h$, $h$Excess, damaged or expired stock at a shop.$h$, array[$h$Shop creates the return.$h$,$h$HQ receives — stock and the shop's account move only then.$h$]::text[], $h$Nothing moves until received.$h$, array[]::text[], $h$[]$h$::jsonb, array[$h$inventory$h$,$h$stock-ledger$h$]::text[]),
($h$stock-count$h$, $h$rm$h$, $h$Maal ki asal ginti kar ke system se milana; farq likhna.$h$, $h$Owner, Admin, Warehouse$h$, $h$Mahine ke aakhir; kisi cheez par shak ho.$h$, array[$h$Godam chunein, ginti likhein.$h$,$h$Farq saamne aata hai — wajah likh kar theek karein.$h$]::text[], $h$Har farq ek harkat ban kar Stock Ledger mein jata hai.$h$, array[$h$Farq ko bina wajah ke theek karna.$h$]::text[], $h$[]$h$::jsonb, array[$h$inventory$h$,$h$stock-ledger$h$]::text[]),
($h$stock-count$h$, $h$en$h$, $h$Physical count against the system; record differences.$h$, $h$Owner, Admin, Warehouse$h$, $h$Month end; when in doubt.$h$, array[$h$Pick the warehouse, enter counts.$h$,$h$Explain and post differences.$h$]::text[], $h$Each difference becomes a ledger movement.$h$, array[]::text[], $h$[]$h$::jsonb, array[$h$inventory$h$,$h$stock-ledger$h$]::text[]),
($h$inventory.warehouses$h$, $h$rm$h$, $h$Godam ki fehrist: naam, code, branch, pata. Naya godam yahin se.$h$, $h$Owner, Admin$h$, $h$Naya godam ya shop ka store banana ho.$h$, array[$h$Naam, code (MAIN har branch ka asal godam), branch, pata.$h$]::text[], $h$Purchase aur intake maal isi godam mein daalte hain.$h$, array[$h$Ek branch ke do MAIN godam.$h$]::text[], $h$[]$h$::jsonb, array[$h$inventory$h$]::text[]),
($h$inventory.warehouses$h$, $h$en$h$, $h$Warehouse master.$h$, $h$Owner, Admin$h$, $h$Adding a warehouse or shop store.$h$, array[$h$Name, code (MAIN = a branch's main store), branch, address.$h$]::text[], $h$Purchases and intake land in this warehouse.$h$, array[$h$Two MAIN warehouses on one branch.$h$]::text[], $h$[]$h$::jsonb, array[$h$inventory$h$]::text[]),
($h$inventory.receiving$h$, $h$rm$h$, $h$Jo maal aana hai, ek nazar mein: manzoor shuda supplier purchases (yahin ginein) aur shop orders ki GRN qatar.$h$, $h$Warehouse, Owner, Admin$h$, $h$Maal aaye — supplier ka ya shop ke order ka.$h$, array[$h$Supplier purchase par 'Maal Aa Gaya' — theek aaya / toota / kam, tasveer, note.$h$,$h$Shop order ke liye 'GRN ki Qatar' kholein.$h$]::text[], $h$Ginte hi stock charhta hai; supplier ka dena utne ka jitna theek aaya.$h$, array[$h$Manzoori baqi purchase ko receive karne ki koshish.$h$]::text[], $h$[]$h$::jsonb, array[$h$purchases$h$,$h$purchases.grn$h$,$h$inventory$h$]::text[]),
($h$inventory.receiving$h$, $h$en$h$, $h$Everything waiting to be counted in: approved supplier purchases and shop-order GRNs.$h$, $h$Warehouse, Owner, Admin$h$, $h$Goods arrive.$h$, array[$h$Supplier purchase: 'Goods Received' — OK / damaged / short, photo, note.$h$,$h$Shop orders: open the GRN queue.$h$]::text[], $h$Stock rises on count; supplier owed for OK units only.$h$, array[]::text[], $h$[]$h$::jsonb, array[$h$purchases$h$,$h$purchases.grn$h$,$h$inventory$h$]::text[]),
($h$purchases.grn$h$, $h$rm$h$, $h$Shop ke orders jo dispatch ho chuke aur receive hone baqi hain (GRN).$h$, $h$Shop staff, Warehouse$h$, $h$Godam se bheja maal shop par pahunche.$h$, array[$h$Order kholein, har line par theek aaya aur toota likhein; kam khud nikalta hai.$h$,$h$Submit — farq ho to warehouse wajah likhta hai, finance final karta hai.$h$]::text[], $h$Shop ka stock tab barhta hai; kami/toote ka paisa alag katta hai.$h$, array[$h$Toote ko theek mein ginna.$h$]::text[], $h$[]$h$::jsonb, array[$h$inventory.receiving$h$,$h$agri-returns$h$]::text[]),
($h$purchases.grn$h$, $h$en$h$, $h$Shop orders dispatched and awaiting receipt (GRN).$h$, $h$Shop staff, Warehouse$h$, $h$Goods from the warehouse reach the shop.$h$, array[$h$Open the order, enter OK and damaged per line.$h$,$h$Submit — discrepancies go to warehouse then finance.$h$]::text[], $h$Shop stock rises; short/damaged value is deducted.$h$, array[]::text[], $h$[]$h$::jsonb, array[$h$inventory.receiving$h$,$h$agri-returns$h$]::text[]),
($h$reports.inventory$h$, $h$rm$h$, $h$Stock ka khulasa: har branch mein kitna maal, kitni qeemat, kam stock.$h$, $h$Owner, Admin, Finance$h$, $h$Mahine ki report; qeemat ka andaza.$h$, array[$h$Branch/godam chunein.$h$,$h$Qeemat = tadad × trade rate.$h$]::text[], $h$Kam stock wali cheezein 'Kya Mangwana Hai' par sujhaav ke sath.$h$, array[$h$Trade rate baqi wali cheez ki qeemat 0 samajhna — wo 'baqi' hai, sifar nahi.$h$]::text[], $h$[]$h$::jsonb, array[$h$inventory$h$,$h$products.reorder$h$]::text[]),
($h$reports.inventory$h$, $h$en$h$, $h$Stock summary and valuation by branch.$h$, $h$Owner, Admin, Finance$h$, $h$Monthly reporting.$h$, array[$h$Pick a branch.$h$,$h$Value = qty × trade rate.$h$]::text[], $h$Low stock items get suggestions on Reorder.$h$, array[$h$Reading a pending trade rate as 0.$h$]::text[], $h$[]$h$::jsonb, array[$h$inventory$h$,$h$products.reorder$h$]::text[]),
($h$product-masters$h$, $h$rm$h$, $h$Qismein, brand aur companies — products ko tarteeb dene ke khane.$h$, $h$Owner, Admin$h$, $h$Nayi qism ya brand chahiye.$h$, array[$h$Tab chunein: Categories | Brands | Companies.$h$,$h$Naam likh kar banayein.$h$]::text[], $h$Products par qism ke tab isi se bante hain.$h$, array[$h$Ek hi qism do naam se.$h$]::text[], $h$[]$h$::jsonb, array[$h$products$h$]::text[]),
($h$product-masters$h$, $h$en$h$, $h$Categories, brands and companies.$h$, $h$Owner, Admin$h$, $h$A new category or brand is needed.$h$, array[$h$Pick a tab.$h$,$h$Add by name.$h$]::text[], $h$Category tabs on Products come from here.$h$, array[]::text[], $h$[]$h$::jsonb, array[$h$products$h$]::text[]),
($h$categories$h$, $h$rm$h$, $h$Qismein, brand aur companies — products ko tarteeb dene ke khane.$h$, $h$Owner, Admin$h$, $h$Nayi qism ya brand chahiye.$h$, array[$h$Tab chunein: Categories | Brands | Companies.$h$,$h$Naam likh kar banayein.$h$]::text[], $h$Products par qism ke tab isi se bante hain.$h$, array[$h$Ek hi qism do naam se.$h$]::text[], $h$[]$h$::jsonb, array[$h$products$h$]::text[]),
($h$categories$h$, $h$en$h$, $h$Categories, brands and companies.$h$, $h$Owner, Admin$h$, $h$A new category or brand is needed.$h$, array[$h$Pick a tab.$h$,$h$Add by name.$h$]::text[], $h$Category tabs on Products come from here.$h$, array[]::text[], $h$[]$h$::jsonb, array[$h$products$h$]::text[]),
($h$brands$h$, $h$rm$h$, $h$Qismein, brand aur companies — products ko tarteeb dene ke khane.$h$, $h$Owner, Admin$h$, $h$Nayi qism ya brand chahiye.$h$, array[$h$Tab chunein: Categories | Brands | Companies.$h$,$h$Naam likh kar banayein.$h$]::text[], $h$Products par qism ke tab isi se bante hain.$h$, array[$h$Ek hi qism do naam se.$h$]::text[], $h$[]$h$::jsonb, array[$h$products$h$]::text[]),
($h$brands$h$, $h$en$h$, $h$Categories, brands and companies.$h$, $h$Owner, Admin$h$, $h$A new category or brand is needed.$h$, array[$h$Pick a tab.$h$,$h$Add by name.$h$]::text[], $h$Category tabs on Products come from here.$h$, array[]::text[], $h$[]$h$::jsonb, array[$h$products$h$]::text[]),
($h$companies$h$, $h$rm$h$, $h$Qismein, brand aur companies — products ko tarteeb dene ke khane.$h$, $h$Owner, Admin$h$, $h$Nayi qism ya brand chahiye.$h$, array[$h$Tab chunein: Categories | Brands | Companies.$h$,$h$Naam likh kar banayein.$h$]::text[], $h$Products par qism ke tab isi se bante hain.$h$, array[$h$Ek hi qism do naam se.$h$]::text[], $h$[]$h$::jsonb, array[$h$products$h$]::text[]),
($h$companies$h$, $h$en$h$, $h$Categories, brands and companies.$h$, $h$Owner, Admin$h$, $h$A new category or brand is needed.$h$, array[$h$Pick a tab.$h$,$h$Add by name.$h$]::text[], $h$Category tabs on Products come from here.$h$, array[]::text[], $h$[]$h$::jsonb, array[$h$products$h$]::text[]),
($h$products.labels$h$, $h$rm$h$, $h$Jin cheezon par barcode nahi, un ke liye apna barcode (200 se shuru) banana aur label chhaapna.$h$, $h$Owner, Admin, Warehouse, Sales$h$, $h$Counter par cheez naam se dhoondni paRe.$h$, array[$h$'Sab ke liye apna barcode banayein' ek dafa.$h$,$h$Products chunein, ginti likhein, 'Label chhaapein'.$h$,$h$Label par naam, pack, rate, barcode.$h$]::text[], $h$Scanner par ye barcode aam barcode ki tarah chalta hai. Company ka asal barcode mile to likh dein, purana label phir bhi chalega.$h$, array[$h$Company ka barcode maujood ho to bhi apna banana — zaroorat nahi.$h$]::text[], $h$[]$h$::jsonb, array[$h$products.setup$h$,$h$pos$h$]::text[]),
($h$products.labels$h$, $h$en$h$, $h$Internal barcodes (200…) and label printing for items without one.$h$, $h$Owner, Admin, Warehouse, Sales$h$, $h$Items must be searched by name at the counter.$h$, array[$h$Make internal barcodes for all.$h$,$h$Pick products, set copies, print.$h$]::text[], $h$Scans like any barcode; a later manufacturer code does not break old labels.$h$, array[]::text[], $h$[]$h$::jsonb, array[$h$products.setup$h$,$h$pos$h$]::text[]),
($h$products.reorder$h$, $h$rm$h$, $h$Bikri ki raftaar se: kitne din ka stock baqi, kitna mangwayein. Sujhaav hai, hukm nahi.$h$, $h$Owner, Admin, Warehouse, Purchase staff$h$, $h$Hafte mein ek dafa; ya jab kuch khatam hone lage.$h$, array[$h$Halat dekhein: khatam / 7 din se kam / 21 din se kam.$h$,$h$Tadad, rate, supplier theek karein, qatarein chunein.$h$,$h$'Purchase draft banayein' — har supplier ki alag, manzoori ke liye.$h$]::text[], $h$Purchase manzoor → Receiving → stock.$h$, array[$h$Jis ki bikri sifar hai us ke 'din baqi' ko sifar samajhna — wahan '—' hai, hisaab banta hi nahi.$h$]::text[], $h$[]$h$::jsonb, array[$h$purchases$h$,$h$inventory$h$]::text[]),
($h$products.reorder$h$, $h$en$h$, $h$From sales velocity: days of stock left and how much to order. Suggestions, not orders.$h$, $h$Owner, Admin, Warehouse, Purchase staff$h$, $h$Weekly, or when items run low.$h$, array[$h$Read the state: out / under 7 days / under 21.$h$,$h$Fix qty, cost, supplier; tick rows.$h$,$h$Make purchase drafts — one per supplier.$h$]::text[], $h$Approve → Receiving → stock.$h$, array[$h$Reading '—' days as zero.$h$]::text[], $h$[]$h$::jsonb, array[$h$purchases$h$,$h$inventory$h$]::text[]),
($h$products.rates_baqi$h$, $h$rm$h$, $h$Jin products ka sale ya trade rate abhi nahi mila — jab tak sale rate na ho, bikte nahi.$h$, $h$Owner, Admin, Warehouse$h$, $h$Sheet charhne ke baad; POS par cheez na mile.$h$, array[$h$Jo rate maloom hai bharein, Save.$h$]::text[], $h$Rate bharte hi POS par aa jata hai.$h$, array[$h$0 likhna.$h$]::text[], $h$[]$h$::jsonb, array[$h$products.setup$h$]::text[]),
($h$products.rates_baqi$h$, $h$en$h$, $h$Products still without a sale or trade rate; no sale until the sale rate exists.$h$, $h$Owner, Admin, Warehouse$h$, $h$After imports.$h$, array[$h$Fill known rates, Save.$h$]::text[], $h$Appears on POS immediately.$h$, array[$h$Typing 0.$h$]::text[], $h$[]$h$::jsonb, array[$h$products.setup$h$]::text[]),
($h$products.import$h$, $h$rm$h$, $h$CSV sheet se bahut se products ek sath: naye bante hain, purane ka rate badalta hai, stock bhi charh sakta hai.$h$, $h$Owner, Admin, Warehouse$h$, $h$Nayi dukan ka poora maal; mahine ki rate list.$h$, array[$h$CSV banayein (xlsx nahi): naam, pack, trade, sale, thok, expiry, qty.$h$,$h$Preview mein har qatar dekhein — edit kar sakte hain, chhoR sakte hain.$h$,$h$Stock ho to godam aur zaria chunein: supplier se (purchase banegi) ya shuru ka.$h$]::text[], $h$Rate baqi wale Product Setup par; supplier wali purchase manzoori par.$h$, array[$h$.xlsx charhana — pehle CSV mein save karein.$h$,$h$Ek naam ke do products — pack size lagayein.$h$,$h$Tareekh 5/9 ko 9 May samajhna — sheet mein din/mahina/saal likhein.$h$]::text[], $h$[{"q": "Google Sheet se kaise?", "a": "File → Download → CSV."}]$h$::jsonb, array[$h$products$h$,$h$products.setup$h$]::text[]),
($h$products.import$h$, $h$en$h$, $h$Bulk products from a CSV: new ones are created, existing rates updated, stock can be added.$h$, $h$Owner, Admin, Warehouse$h$, $h$A new shop's full list; monthly rate lists.$h$, array[$h$Prepare a CSV.$h$,$h$Check every row in the preview.$h$,$h$For stock, pick the warehouse and source.$h$]::text[], $h$Missing rates go to Product Setup; supplier stock creates a purchase for approval.$h$, array[$h$Uploading .xlsx.$h$,$h$Duplicate names.$h$]::text[], $h$[]$h$::jsonb, array[$h$products$h$,$h$products.setup$h$]::text[]),
($h$products.propose$h$, $h$rm$h$, $h$Staff naya product tajweez kare; Admin manzoor kare tab live hota hai.$h$, $h$Sales, Shop staff$h$, $h$Koi cheez fehrist mein na ho aur aap ko banane ki ijazat na ho.$h$, array[$h$Naam, qism, rate likh kar bhejein.$h$]::text[], $h$Admin 'Manzoori Baqi' tab par dekhega.$h$, array[$h$Pehle dhoondna bhool jana — shayad pehle se hai.$h$]::text[], $h$[]$h$::jsonb, array[$h$products.pending$h$,$h$products.setup$h$]::text[]),
($h$products.propose$h$, $h$en$h$, $h$Staff propose a product; Admin approves before it goes live.$h$, $h$Sales, Shop staff$h$, $h$An item is missing and you cannot create products.$h$, array[$h$Enter name, category, rate; submit.$h$]::text[], $h$Admin reviews under Pending Approval.$h$, array[$h$Not searching first.$h$]::text[], $h$[]$h$::jsonb, array[$h$products.pending$h$,$h$products.setup$h$]::text[]),
($h$products.pending$h$, $h$rm$h$, $h$Staff ke tajweez kiye products — dekh kar manzoor ya radd.$h$, $h$Owner, Admin$h$, $h$Roz ek dafa.$h$, array[$h$Har qatar dekhein, rate theek karein, manzoor.$h$]::text[], $h$Manzoor hote hi products mein aur POS par.$h$, array[$h$Bina rate dekhe manzoor.$h$]::text[], $h$[]$h$::jsonb, array[$h$products.propose$h$,$h$products.setup$h$]::text[]),
($h$products.pending$h$, $h$en$h$, $h$Products proposed by staff — approve or reject.$h$, $h$Owner, Admin$h$, $h$Daily.$h$, array[$h$Check each, fix rates, approve.$h$]::text[], $h$Approved products go live.$h$, array[]::text[], $h$[]$h$::jsonb, array[$h$products.propose$h$,$h$products.setup$h$]::text[]),
($h$products.pending-edits$h$, $h$rm$h$, $h$Staff ki tajweez ki hui tabdeeliyan (rate, naam) — manzoor ya radd.$h$, $h$Owner, Admin$h$, $h$Roz ek dafa.$h$, array[$h$Purana aur naya adad sath dekhein, manzoor.$h$]::text[], $h$Manzoori par product badal jata hai.$h$, array[]::text[], $h$[]$h$::jsonb, array[$h$products.setup$h$]::text[]),
($h$products.pending-edits$h$, $h$en$h$, $h$Edits proposed by staff — approve or reject.$h$, $h$Owner, Admin$h$, $h$Daily.$h$, array[$h$Compare old and new, approve.$h$]::text[], $h$The product changes on approval.$h$, array[]::text[], $h$[]$h$::jsonb, array[$h$products.setup$h$]::text[]),
($h$products.catalog-export$h$, $h$rm$h$, $h$Products ki fehrist sheet mein nikalna — supplier ko bhejne ya print ke liye.$h$, $h$Owner, Admin, Sales$h$, $h$Rate list bhejni ho.$h$, array[$h$Qism chunein, Export.$h$]::text[], $h$Sheet download hoti hai.$h$, array[]::text[], $h$[]$h$::jsonb, array[$h$products$h$]::text[]),
($h$products.catalog-export$h$, $h$en$h$, $h$Export the product list as a sheet.$h$, $h$Owner, Admin, Sales$h$, $h$Sharing a rate list.$h$, array[$h$Pick a category, Export.$h$]::text[], $h$Downloads a sheet.$h$, array[]::text[], $h$[]$h$::jsonb, array[$h$products$h$]::text[]),
($h$pos$h$, $h$rm$h$, $h$Counter par bikri: scan ya naam se cheez, bill, cash ya khata.$h$, $h$Sales, Shop staff$h$, $h$Har bikri.$h$, array[$h$Barcode scan karein ya naam likhein.$h$,$h$Tadad theek karein, thok gahak ho to thok rate khud lagta hai.$h$,$h$Cash ya khata chunein, bill banayein.$h$]::text[], $h$Stock khud kam hota hai; khata gahak ke khate mein.$h$, array[$h$Jis cheez ka rate baqi hai wo nahi bikti — Product Setup par rate bharein.$h$,$h$Bina barcode wali cheez — Barcode Label se apna barcode.$h$]::text[], $h$[{"q": "Cheez POS par nazar nahi aa rahi?", "a": "Ya rate baqi hai, ya stock is godam mein nahi. Product Setup aur Stock dekhein."}]$h$::jsonb, array[$h$products.setup$h$,$h$products.labels$h$,$h$inventory$h$]::text[]),
($h$pos$h$, $h$en$h$, $h$Counter sales: scan or search, bill, cash or khata.$h$, $h$Sales, Shop staff$h$, $h$Every sale.$h$, array[$h$Scan or type the name.$h$,$h$Fix quantity; wholesale rate applies to wholesale customers.$h$,$h$Cash or khata, make the bill.$h$]::text[], $h$Stock drops automatically.$h$, array[$h$Items without a sale rate cannot be sold.$h$]::text[], $h$[]$h$::jsonb, array[$h$products.setup$h$,$h$products.labels$h$,$h$inventory$h$]::text[]),
($h$suppliers$h$, $h$rm$h$, $h$Supplier ki fehrist, un ka dena, aur adaigi likhna.$h$, $h$Owner, Admin, Finance, Purchase staff$h$, $h$Naya supplier; adaigi bhejni ho.$h$, array[$h$Supplier kholein → statement → 'Adaigi likhein' (raqam, tareekh, tareeqa, slip).$h$]::text[], $h$Dena khud dobara banta hai: received purchases − adaigiyan.$h$, array[$h$Dena haath se likhne ki koshish — wo hisaab se banta hai.$h$]::text[], $h$[]$h$::jsonb, array[$h$purchases.bills$h$,$h$purchases$h$]::text[]),
($h$suppliers$h$, $h$en$h$, $h$Supplier list, payables, and recording payments.$h$, $h$Owner, Admin, Finance, Purchase staff$h$, $h$New supplier; sending a payment.$h$, array[$h$Open supplier → statement → Record payment.$h$]::text[], $h$Payable recomputes: received purchases − payments.$h$, array[]::text[], $h$[]$h$::jsonb, array[$h$purchases.bills$h$,$h$purchases$h$]::text[]),
($h$my-work$h$, $h$rm$h$, $h$Aap ka ghar: aaj ke kaam, aur jo safhe aap ke hain.$h$, $h$Har staff$h$, $h$Login ke baad.$h$, array[$h$Card par apna kaam chunein.$h$,$h$Upar ki patti se POS ya notifications.$h$]::text[], $h$Jo baqi hai wo yahan ginti ke sath aayega (agla qadam: Needs Attention).$h$, array[]::text[], $h$[{"q": "Mujhe koi safha nahi dikhta?", "a": "Admin ne ijazat nahi di. Un se kahein."}]$h$::jsonb, array[]::text[]),
($h$my-work$h$, $h$en$h$, $h$Your home: today's work and your pages.$h$, $h$All staff$h$, $h$After login.$h$, array[$h$Pick a card.$h$,$h$Use the top bar for POS and notifications.$h$]::text[], $h$Pending work will appear here with counts.$h$, array[]::text[], $h$[]$h$::jsonb, array[]::text[]),
($h$bridge-ai$h$, $h$rm$h$, $h$Bridge AI se sawal: bikri, stock, dena, kya mangwana hai; aur shop order ka draft.$h$, $h$Owner, Admin, Manager$h$, $h$Jaldi jawab chahiye jo report mein dhoondna paRe.$h$, array[$h$Roman Urdu mein poochein: 'kya mangwana hai?', 'Mahabali ke liye DAP 20 mangwa do'.$h$,$h$AI draft banata hai, aap Action Requests par manzoor karte hain.$h$]::text[], $h$AI kabhi khud kuch mehfooz nahi karta.$h$, array[$h$AI ke adad ko bina dekhe maan lena.$h$]::text[], $h$[]$h$::jsonb, array[$h$products.reorder$h$]::text[]),
($h$bridge-ai$h$, $h$en$h$, $h$Ask Bridge AI about sales, stock, payables, reorder; draft shop orders.$h$, $h$Owner, Admin, Manager$h$, $h$Quick answers.$h$, array[$h$Ask in plain words.$h$,$h$AI drafts; you approve under Action Requests.$h$]::text[], $h$AI never saves anything itself.$h$, array[]::text[], $h$[]$h$::jsonb, array[$h$products.reorder$h$]::text[]),
($h$crm$h$, $h$rm$h$, $h$Gahak aur un ka khata: kaun kitna dena hai, adaigi likhna, thok wali dukanein.$h$, $h$Sales, Owner, Admin, Finance$h$, $h$Khata gahak; thok dukan ka rate.$h$, array[$h$Gahak kholein, khata dekhein, adaigi likhein.$h$,$h$Thok dukan ho to qism 'wholesale_shop' — POS par thok rate khud lagta hai.$h$]::text[], $h$POS ka khata yahin jama hota hai.$h$, array[$h$Ek gahak do naam se.$h$]::text[], $h$[]$h$::jsonb, array[$h$pos$h$]::text[]),
($h$crm$h$, $h$en$h$, $h$Customers and their khata; wholesale shops.$h$, $h$Sales, Owner, Admin, Finance$h$, $h$Credit customers; wholesale pricing.$h$, array[$h$Open customer, see khata, record payment.$h$,$h$Mark wholesale shops.$h$]::text[], $h$POS khata accrues here.$h$, array[]::text[], $h$[]$h$::jsonb, array[$h$pos$h$]::text[]),
($h$cash-close$h$, $h$rm$h$, $h$Raat ko cash ginna aur system se milana.$h$, $h$Sales, Shop staff, Finance$h$, $h$Har din band karte waqt.$h$, array[$h$Note ginein, system ka adad saamne, farq likhein.$h$]::text[], $h$Farq ki wajah Finance dekhta hai.$h$, array[$h$Farq chhupane ke liye adad badalna.$h$]::text[], $h$[]$h$::jsonb, array[$h$pos$h$]::text[]),
($h$cash-close$h$, $h$en$h$, $h$Count the cash at night against the system.$h$, $h$Sales, Shop staff, Finance$h$, $h$Daily close.$h$, array[$h$Count, compare, note the difference.$h$]::text[], $h$Finance reviews differences.$h$, array[]::text[], $h$[]$h$::jsonb, array[$h$pos$h$]::text[])
) as v(feature_key, lang, purpose, who_uses, when_use, how_steps, next_step, mistakes, faq, related)
where exists (select 1 from features f where f.key = v.feature_key)
on conflict (feature_key, lang) do update set
  purpose = excluded.purpose, who_uses = excluded.who_uses, when_use = excluded.when_use,
  how_steps = excluded.how_steps, next_step = excluded.next_step, mistakes = excluded.mistakes,
  faq = excluded.faq, related = excluded.related, updated_at = now();
