-- =====================================================================
-- AgriBridge — Migration 283: Finance aur Admin ke safhon ka help
-- =====================================================================
-- 282 mein rozana ke 14 safhe likhe gaye the. Yahan Finance (paisa
-- kahan hai, cash kis ke paas, rissaav, ghair-maamooli tarteeb, bank,
-- batwe, udhaar, qarze) aur Admin (users, ijazat, department, shaakh,
-- dukan, record) ke 32 safhe likhe gaye hain.
--
-- Usool wohi hai: sirf wo qadam likhe gaye hain jo code se jaanch liye
-- gaye. Andaze se qadam likhna sab se bura raasta hai -- ghalat qadam
-- bande ko ghalat kaam par le jate hain, aur wo ghalti us ke naam par
-- likhi jati hai.
-- =====================================================================

insert into feature_help (feature_key, lang, purpose, who_uses, when_use, how_steps, next_step, mistakes) values
('money-trail','rm',
 'Paisa kahan hai: har khate, bank aur haath mein maujood raqam ek hi safhe par.',
 'Owner, Admin, Finance.',
 'Jab jaanna ho ke kul paisa kitna hai aur kis jagah paRa hai.',
 array['Safha kholein -- har jagah ki raqam alag alag nazar aayegi.','Kisi jagah par click kar ke us ki tafseel dekhein.'],
 'Farq lage to Roz ka Milaan aur Bank Milaan se jaanchein.',
 array['Ye adad khud nahi likha jata -- entries se banta hai. Ghalat lage to entry theek karein, adad nahi.']),

('cash-custody','rm',
 'Kis ke paas cash: kis mulazim ke zimme is waqt kitni raqam hai.',
 'Owner, Admin, Finance, Manager.',
 'Roz shaam, aur jab kisi se cash lena ho.',
 array['Fehrist kholein: naam aur us ke zimme raqam.','Zyada raqam kisi ek ke paas ruki ho to handover karwayein.'],
 'Cash Haath Badalna se raqam agle bande ke hawale karein.',
 array['Zimmedari zubani na badlein -- handover darj hona chahiye, warna nuqsan par kisi ka naam nahi hota.']),

('leakage','rm',
 'Paisa kahan se nikal raha hai: wo jagahein jahan nuqsan ya rissaav ho raha hai.',
 'Owner aur Admin.',
 'Hafte mein ek dafa, aur jab nafa kam lage.',
 array['Fehrist kholein: har qisam ka nuqsan alag.','Sab se bari raqam pehle dekhein aur us ki jarh tak jayein.'],
 'Jo jagah pakRi jaye us ka qanoon ya tareeqa badlein.',
 array['Sirf dekh kar chhoR dena is safhe ko bekar kar deta hai -- har qatar par faisla likha jana chahiye.']),

('anomalies','rm',
 'Ghair-maamooli tarteeb: aise lein-dein jo aam se hat kar hain.',
 'Owner aur Admin.',
 'Hafte mein ek dafa.',
 array['Fehrist kholein.','Har qatar dekhein: ye waqai ghalat hai ya sirf ghair-maamooli.','Jo ghalat ho us ki tehqeeq karein.'],
 'Ghalat mile to Audit Trail se poora silsila dekhein.',
 array['Har ghair-maamooli cheez chori nahi hoti -- pehle poochein, phir faisla karein.']),

('quantity-money','rm',
 'Miqdar aur paisa: maal kitna aaya/gaya aur us ke saamne kitni raqam chali.',
 'Owner, Admin, Finance.',
 'Jab shak ho ke maal aur paise ka hisaab barabar nahi.',
 array['Arsa chunein.','Miqdar aur raqam ka milaan dekhein.','Farq wali qatarein kholein.'],
 'Farq mile to us purchase ya bikri ka record kholein.',
 array['Miqdar aur paisa alag alag jagah se aate hain -- farq ka matlab hamesha chori nahi, aksar adhoori entry hoti hai.']),

('branch-credit','rm',
 'Shop ka udhaar aur advance: kis dukan ki kitni hadd hai aur kitna istemal ho chuka.',
 'Owner, Admin, Finance.',
 'Naya order manzoor karte waqt aur mahine ke aakhir mein.',
 array['Dukan chunein.','Us ki hadd (limit) aur maujooda baqi dekhein.','Zaroorat ho to hadd badlein -- wajah likh kar.'],
 'Hadd se zyada order Finance ki tasdeeq par ruk jata hai.',
 array['Sab dukanon ki hadd sifar chhoR dena order rok deta hai -- shuru mein hadd zaroor set karein.']),

('company-expenses','rm',
 'Company ka kharcha: darkhwast, manzoori aur adaigi.',
 'Har staff darkhwast de sakta hai; Owner/Admin manzoor karte hain.',
 'Jab koi kharcha karna ho ya ho chuka ho.',
 array['Kharche ki qisam, raqam aur wajah likhein.','Raseed ki tasveer lagayein.','Manzoori ke liye bhejein.'],
 'Manzoori ke baad kharcha cash book mein khud aa jata hai.',
 array['Bina raseed ke bari raqam manzoor na karein.','Apna hi kharcha khud manzoor karna SoD ke khilaf hai.']),

('credit-requests','rm',
 'Udhaar ki darkhwastein: kis ne hadd barhane ya naya udhaar maanga hai.',
 'Finance aur Owner/Admin.',
 'Jab koi gahak ya dukan hadd barhwana chahe.',
 array['Darkhwast kholein.','Us ki purani adaigi ka record dekhein.','Manzoor ya radd karein -- wajah ke sath.'],
 'Manzoori ke baad nayi hadd Shop ka Udhaar par nazar aati hai.',
 array['Sirf zubani yaqeen par hadd na barhayein -- record dekhein.']),

('finance.banks','rm',
 'Bank ke khate: kaun se khate hain aur un mein kitna hai.',
 'Finance aur Owner/Admin.',
 'Naya khata khulne par, ya balance dekhne ke liye.',
 array['Khata jorein: naam, number, shuruati balance.','Har lein-den us khate par darj hota hai.'],
 'Statement aane par Bank Milaan karein.',
 array['Balance haath se na badlein -- wo entries se banta hai.']),

('finance.payment-mapping','rm',
 'Adaigi ka tareeqa: cash, bank ya cheque -- kaun sa tareeqa kis khate par jata hai.',
 'Finance aur Admin.',
 'Shuru mein ek dafa, aur naya khata banne par.',
 array['Har tareeqe ke saamne khata chunein.','Mehfooz karein.'],
 'Is ke baad har adaigi khud sahih khate par chali jati hai.',
 array['Ghalat khata chunne se poora mahina ghalat jagah post hota rehta hai -- shuru mein ek dafa dhyan se karein.']),

('finance.queue','rm',
 'Finance ki qatar: jo maali kaam tasdeeq ke muntazir hain.',
 'Finance ka staff.',
 'Roz.',
 array['Qatar kholein.','Har cheez ki raseed/tafseel jaanchein.','Tasdeeq karein ya wapas bhejein.'],
 'Tasdeeq ke baad raqam apni jagah post ho jati hai.',
 array['Bina raseed dekhe tasdeeq na karein.']),

('payouts','rm',
 'Adaigiyan: kis ko kya diya ja raha hai.',
 'Finance.',
 'Jab adaigi ka waqt aaye.',
 array['Fehrist kholein.','Adaigi darj karein: raqam, tareeqa, hawala.','Evidence lagayein.'],
 'Adaigi cash book aur us bande ke khate dono mein jati hai.',
 array['Ek adaigi do jagah darj na karein -- do dafa ginti ho jati hai.']),

('wallets','rm',
 'Batwe: kis ke batwe mein kitni raqam hai.',
 'Finance aur Admin.',
 'Jab batwe ka hisaab dekhna ho.',
 array['Banda ya batwa chunein.','Aane jaane wali raqam dekhein.'],
 'Raqam nikalni ho to us ka apna raasta istemal karein.',
 array['Batwe ka balance haath se na badlein.']),

('my-wallet','rm',
 'Mera batwa: mere zimme aur mere naam ki raqam.',
 'Har mulazim apna.',
 'Kabhi bhi.',
 array['Safha kholein.','Apni raqam aur lein-den dekhein.'],
 'Ghalti lage to finance ko batayein.',
 array['Apna balance khud badalna mumkin nahi -- ye jaan boojh kar hai.']),

('farmer-credit','rm',
 'Kisan ka udhaar: kis kisan par kitna baqi hai.',
 'Sales, finance aur manager.',
 'Udhaar dete waqt aur wusooli par.',
 array['Kisan chunein.','Us ka purana record dekhein.','Nayi wusooli darj karein.'],
 'Bara udhaar ho to wusooli ka waqt tay karein.',
 array['Bina purana record dekhe naya udhaar na dein.']),

('farmer-loans','rm',
 'Kisan ke qarze: kis ko kya diya gaya aur wapsi kaisi hai.',
 'Finance aur manager.',
 'Qarz dete waqt aur wapsi par.',
 array['Kisan aur raqam chunein.','Wapsi ki tarteeb likhein.','Har wapsi darj karein.'],
 'Wapsi na aaye to kisan se raabta karein.',
 array['Qarz aur udhaar do alag cheezein hain -- inhen mila kar na likhein.']),

('buyers','rm',
 'Kharidar: jo hum se maal khareedte hain.',
 'Sales aur manager.',
 'Naya kharidar aaye ya us ki maloomat badle.',
 array['Number se pehle dhoondein -- aksar wo pehle se maujood hota hai.','Na mile to naya banayein: naam, number, ilaqa.'],
 'Us ka khata Khata ke safhe par khulta hai.',
 array['Ek kharidar do dafa na banayein -- us ka udhaar do jagah bat jata hai.']),

('dealers','rm',
 'Dealer: jin ke zariye maal aage jata hai.',
 'Sales aur manager.',
 'Naya dealer aaye ya us ki maloomat badle.',
 array['Naam, number aur ilaqa likhein.','Us ki hadd aur rate tay karein.'],
 'Dealer ke order us ke apne safhe par.',
 array['Ek dealer do dafa na banayein.']),

('dealer-orders','rm',
 'Dealer ke order: kaun sa order kis darje par hai.',
 'Sales aur manager.',
 'Jab dealer order de.',
 array['Order kholein.','Maal aur raqam jaanchein.','Aage ka qadam chunein.'],
 'Manzoori ke baad maal bhejne ka qadam aata hai.',
 array['Jis ne order banaya wo khud manzoor nahi kar sakta.']),

('produce-orders','rm',
 'Fasal ke order: kisan se fasal lene ke order.',
 'Anaj/procurement ka staff.',
 'Jab fasal ka sauda ho.',
 array['Kisan, fasal aur miqdar likhein.','Rate tay karein.','Order mehfooz karein.'],
 'Maal aane par godam mein ginti karein.',
 array['Rate zubani tay kar ke bhool jana jhagRe ki jarh banta hai -- likh dein.']),

('bridge-orders','rm',
 'Order: platform par aane wale order.',
 'Sales.',
 'Jab naya order aaye.',
 array['Order kholein.','Tafseel jaanchein.','Aage ka qadam chunein.'],
 'Manzoori ke baad maal bhejne ka silsila.',
 array['Purane order band karna na bhoolein -- warna qatar lambi hoti rehti hai.']),

('shops','rm',
 'Dukanein: kaun kaun si dukanein hain.',
 'Owner aur Admin.',
 'Nayi dukan khulne par.',
 array['Naam, jagah aur zimmedar likhein.','Us ka godam bhi banayein.'],
 'Dukan ke staff aur hadd alag safhon par.',
 array['Godam banaye baghair dukan ko maal nahi bheja ja sakta.']),

('branches','rm',
 'Shaakhein: idare ki shaakhein aur un ki maloomat.',
 'Owner aur Admin.',
 'Nayi shaakh banne par.',
 array['Naam aur tafseel likhein.','Zimmedar tay karein.'],
 'Shaakh ki jagah (location) alag safhe par darj hoti hai.',
 array['Shaakh ki jagah darj na hone se hazri ka faasla nahi naapa jata.']),

('branches.locations','rm',
 'Shaakh ki jagah: naqshe par asal jagah aur us ka daira.',
 'Admin aur HR.',
 'Ek dafa har shaakh ke liye.',
 array['Shaakh chunein.','Naqshe par jagah lagayein.','Daira (meter) tay karein -- default 200m.'],
 'Us ke baad hazri ka faasla khud naapa jata hai.',
 array['Jagah darj na ho to hazri to lagti hai magar faasla "maloom nahi" rehta.']),

('shop-rent','rm',
 'Dukan ka kiraya aur bill: kis dukan ka kya kharcha hai.',
 'Finance aur Admin.',
 'Har mahine.',
 array['Dukan chunein.','Kiraya aur bill darj karein.','Adaigi ke baad us ka nishan lagayein.'],
 'Ye kharcha nafa nuqsan mein khud aa jata hai.',
 array['Adaigi ke baghair nishan na lagayein.']),

('users','rm',
 'Users aur role: kis ka login hai aur wo kaun hai.',
 'Owner, Admin, super admin.',
 'Naya mulazim aaye ya kisi ka kaam badle.',
 array['Naya user banayein ya purana chunein.','Role tay karein.','Fa''aal ya band karein.'],
 'Us ke baad us ki ijazat alag safhe par tay hoti hai.',
 array['Jane wale mulazim ka login band karna na bhoolein.','Ek hi banda do login se kaam na kare -- audit gaddmadd hota hai.']),

('permissions','rm',
 'Ek banday ki ijazat: kis ko kya khulta hai.',
 'Owner aur Admin.',
 'Jab kisi ko naya kaam diya jaye.',
 array['Banda chunein.','Feature ke saamne kaam chunein (dekhna, banana, manzoor karna...).','Data ka daira chunein aur mehfooz karein.'],
 'Bara ikhtiyar dene se pehle takraao ki jaanch dekh lein.',
 array['Zaroorat se zyada ijazat sab se aam ghalti hai -- sirf wohi dein jo us ke kaam ka hai.']),

('departments','rm',
 'Department aur ijazat: kis department ko kaun se safhe.',
 'Owner aur Admin.',
 'Shuru mein, aur jab kaam ki tarteeb badle.',
 array['Department chunein.','Us ke safhe tay karein.','Mehfooz karein.'],
 'Menu isi se banta hai.',
 array['Yahan se hataya gaya safha us department ke har bande se ghayab ho jata hai -- pehle dekh lein kaun istemal kar raha hai.']),

('product-permissions','rm',
 'Product ki ijazat: kaun si cheez kis dukan/branch par chalti hai.',
 'Admin aur product manager.',
 'Nayi cheez aaye ya dukan badle.',
 array['Cheez chunein.','Jagah chunein jahan wo dikhni chahiye.'],
 'POS par wohi cheezein aati hain jo yahan khuli hon.',
 array['Ijazat na hone par cheez POS par nazar nahi aati -- log samajhte hain stock khatam hai.']),

('activity-logs','rm',
 'Kaam ka record: system mein kya kya hua.',
 'Admin.',
 'Tehqeeq ke waqt.',
 array['Arsa ya banda chunein.','Qatarein parhein.'],
 'Maali cheez ho to Audit Trail behtar hai.',
 array['Ye record mitaya nahi ja sakta -- yehi is ka faida hai.']),

('notifications','rm',
 'Ittila''at: system ki taraf se aane wale paighaam.',
 'Har staff apne.',
 'Roz.',
 array['Fehrist kholein.','Parh kar nishan laga dein.'],
 'Jis par kaam ho wo seedha wahan le jata hai.',
 array['Bina parhe sab ko "parh liya" karna kaam chhupa deta hai.']),

('contact-messages','rm',
 'Website ke paighaam: bahar se aane wale sawal.',
 'Admin aur sales.',
 'Roz.',
 array['Paighaam kholein.','Jawab dein ya zimmedar ko dein.'],
 'Kaam ka paighaam ho to lead bana lein.',
 array['Purane paighaam band karna na bhoolein.'])

on conflict (feature_key, lang) do update set
  purpose = excluded.purpose, who_uses = excluded.who_uses, when_use = excluded.when_use,
  how_steps = excluded.how_steps, next_step = excluded.next_step, mistakes = excluded.mistakes,
  updated_at = now();
