-- =====================================================================
-- AgriBridge — Migration 284: HR, Doodh aur Fleet ke safhon ka help
-- =====================================================================
-- 282 (rozana ke 14) aur 283 (finance/admin ke 32) ke baad yahan HR
-- (staff, hazri, chhutti, aazmaishi muddat, team, WhatsApp), Doodh
-- (chiller, walk-in, route, dispatch, billing, fi litre kharcha, tel,
-- generator, marammat) aur Fleet (driver, gaari, meri gaari) ke 26
-- safhe likhe gaye hain.
--
-- Usool wohi: sirf wo qadam jo code se jaanch liye gaye. Jis feature ka
-- amal yaqeen se maloom na ho us ko khali chhoRa jata hai, aur AI ko
-- hidayat hai ke wahan qadam KHUD NA BANAYE.
-- =====================================================================

insert into feature_help (feature_key, lang, purpose, who_uses, when_use, how_steps, next_step, mistakes) values
('hr','rm',
 'Staff ka record: kaun kaam karta hai, us ki maloomat aur kaghazat.',
 'HR aur Admin.',
 'Naya mulazim aaye, ya purane ki maloomat badle.',
 array['Mulazim chunein ya naya banayein.','Naam, phone, CNIC, department aur tankhwah likhein.','Kaghazat lagayein.'],
 'Us ka login Users ke safhe par banta hai.',
 array['Phone aur CNIC theek likhein -- WhatsApp par pehchan inhi do se hoti hai.','Phone badle to WhatsApp ki tasdeeq khud khatam ho jati hai; naya number darj karna zaroori hai.']),

('hr-dashboard','rm',
 'HR ka khulasa: hazri, chhutti aur staff ki halat ek nazar mein.',
 'HR aur Owner/Admin.',
 'Roz subah.',
 array['Aaj ki hazri ka adad dekhein.','Chhutti aur darkhwastein dekhein.'],
 'Kisi qatar par click kar ke us ka safha khulta hai.',
 array['Yahan ke adad khud nahi likhe jate -- asal record se aate hain.']),

('hr.attendance','rm',
 'Hazri: kis din kaun aaya.',
 'HR aur manager.',
 'Roz, aur tankhwah banate waqt.',
 array['Din ya mulazim chunein.','Hazri dekhein aur zaroorat ho to darust karwayein.'],
 'Ghalti par mulazim darkhwast de sakta hai.',
 array['Kisi aur ki hazri apne haath se badalna audit mein nazar aata hai -- darkhwast ka raasta istemal karein.']),

('hr.attendance-board','rm',
 'Hazri board: aaj kaun aaya, kaun nahi -- ek nazar mein.',
 'Manager aur HR.',
 'Har subah.',
 array['Board kholein.','Ghair hazir logon ko dekhein aur poochein.'],
 'Chhutti ho to us ki darkhwast darj karwayein.',
 array['Board sirf tasveer hai; asal record hazri ke safhe par hai.']),

('hr.corrections','rm',
 'Hazri ki darkhwastein: mulazim kehta hai ke us din ka record ghalat hai.',
 'HR aur manager.',
 'Jab koi darkhwast aaye.',
 array['Darkhwast kholein aur wajah parhein.','Record se milaan karein.','Manzoor ya radd karein -- wajah likh kar.'],
 'Manzoori ke baad hazri khud theek ho jati hai.',
 array['Bina record dekhe manzoori dena hazri ka poora nizam bekar kar deta hai.']),

('hr.leave','rm',
 'Chhutti: darkhwast, manzoori aur baqi chhuttiyan.',
 'Har mulazim darkhwast deta hai; manager/HR manzoor karte hain.',
 'Chhutti se pehle.',
 array['Tareekhein aur qisam chunein.','Wajah likhein aur bhejein.','Manager manzoor kare.'],
 'Manzoori ke baad hazri mein wo din chhutti ke tor par lagte hain.',
 array['Chhutti le kar darkhwast na dena tankhwah mein katauti ban jata hai.']),

('hr.probation','rm',
 'Aazmaishi muddat: naye mulazim ka jaiza.',
 'HR aur manager.',
 'Naye mulazim ke pehle mahinon mein.',
 array['Mulazim chunein.','Jaiza likhein.','Faisla darj karein: pakka, muddat barhayein, ya alag.'],
 'Faisle ke baad us ka darja badal jata hai.',
 array['Muddat khatam hone par faisla na karna sab se aam ghalti hai -- mulazim khud pakka samajh leta hai.']),

('hr.team','rm',
 'Team aur reporting: kaun kis ko report karta hai.',
 'HR aur Owner/Admin.',
 'Shuru mein, aur jab tarteeb badle.',
 array['Mulazim chunein.','Us ka manager tay karein.'],
 'Manzoori aur darkhwastein isi tarteeb se jati hain.',
 array['Reporting khali chhoRne se us ki darkhwastein kisi ke paas nahi jatin.']),

('hr.calendar-settings','rm',
 'Chhutti aur waqt: hafte ke din, chhuttiyan aur kaam ka waqt.',
 'HR aur Admin.',
 'Saal mein ek dafa, aur jab chhutti ka elaan ho.',
 array['Kaam ke din aur waqt tay karein.','Sarkari chhuttiyan daalein.'],
 'Hazri aur chhutti ka hisaab isi par chalta hai.',
 array['Chhutti darj na karne se us din ki ghair hazri ghalat gini jati hai.']),

('hr.whatsapp','rm',
 'Staff WhatsApp: kis mulazim ka number tasdeeq shuda hai.',
 'HR aur Admin.',
 'Naya mulazim aaye ya number badle.',
 array['Mulazim ka number aur CNIC darj karein.','Mulazim WhatsApp se tasdeeq kare.'],
 'Tasdeeq ke baad wo WhatsApp se hazri laga sakta hai.',
 array['Number badalne par tasdeeq khud khatam ho jati hai -- ye jaan boojh kar hai, warna purana number chalta rehta.']),

('my-department','rm',
 'Meri team: department head ke liye apni team ka kaam.',
 'Department head.',
 'Roz.',
 array['Team ki fehrist dekhein.','Kis ka kya kaam baqi hai, wo dekhein.'],
 'Ijazat chahiye to darkhwast ka raasta.',
 array['Apni hadd se bara ikhtiyar kisi ko nahi de sakte -- system khud kaat deta hai.']),

('milk-collection','rm',
 'Doodh ka kaam: collection se adaigi tak sab ek jagah.',
 'Doodh ka staff aur manager.',
 'Roz.',
 array['Aaj ka collection dekhein.','Tasdeeq, route aur adaigi ke safhe yahin se khulte hain.'],
 'Roz ka kaam Doodh Jama Karein se shuru hota hai.',
 array['Yahan ke adad khud nahi likhe jate -- entries se bante hain.']),

('milk-collection.chiller','rm',
 'Chiller: thandak, FAT aur miqdar ka record.',
 'Chiller ka staff.',
 'Har collection ke baad.',
 array['Miqdar aur FAT likhein.','Thandak ka darja likhein.'],
 'Dispatch ke waqt yahi adad kaam aate hain.',
 array['FAT andaze se na likhein -- adaigi usi par banti hai.']),

('milk-collection.walk-in','rm',
 'Khud laaya hua doodh: jo kisan apna doodh khud le kar aaye.',
 'Doodh ka staff.',
 'Jab kisan khud doodh laaye.',
 array['Kisan chunein.','Litre aur FAT likhein.','Mehfooz karein.'],
 'Baqi hisaab wahi hai jo route wale doodh ka.',
 array['Route ka aur khud laaya hua doodh mila kar na likhein -- kharche ka hisaab bigaR jata hai.']),

('milk-collection.routes','rm',
 'Route aur kami: kaun sa route kitna doodh laaya aur kitni kami rahi.',
 'Doodh ka manager.',
 'Roz, dispatch ke baad.',
 array['Route chunein.','Uthaya gaya aur pahuncha hua doodh dekhein.','Kami ho to wajah likhein.'],
 'Baar baar kami ho to route ya driver dekhein.',
 array['Kami chhupana sab se mehnga sabaq banta hai -- likh dein, wajah baad mein milti hai.']),

('milk-collection.dispatch','rm',
 'Dispatch: doodh company ya kharidar ko bhejna.',
 'Doodh ka manager.',
 'Har collection ke baad.',
 array['Miqdar aur gaari likhein.','Bhejein.','Pahunchne par tasdeeq karein.'],
 'Pahunchne ke baad billing ka qadam.',
 array['Bheja hua aur pahuncha hua doodh ek nahi -- dono likhein.']),

('milk-collection.billing','rm',
 'Company billing aur nafa: company se kitna mila aur kitna kharch hua.',
 'Doodh ka manager aur finance.',
 'Har bill ke waqt.',
 array['Arsa chunein.','Bheja gaya doodh aur us ki raqam dekhein.','Bill se milaan karein.'],
 'Farq ho to dispatch ke record se jaanchein.',
 array['Bill ko bina milaan ke qabool na karein.']),

('milk-collection.cost-per-liter','rm',
 'Fi litre kharcha: ek litre doodh par kitna kharch aa raha hai.',
 'Doodh ka manager aur Owner.',
 'Mahine mein ek dafa.',
 array['Arsa chunein.','Tel, generator, marammat aur baqi kharche dekhein.','Fi litre kharcha nikale.'],
 'Kharcha barhe to us ki jarh (tel/marammat) dekhein.',
 array['Sab kharche darj na hon to ye adad kam nazar aata hai -- aur faisla ghalat ho jata hai.']),

('milk-collection.fuel','rm',
 'Tel ka hisaab: kis gaari mein kitna tel gaya.',
 'Doodh ka staff.',
 'Har dafa tel daalne par.',
 array['Gaari aur miqdar likhein.','Meter ka adad aur raseed lagayein.'],
 'Fi litre kharche mein yahi raqam jati hai.',
 array['Meter ka adad likhna na bhoolein -- us ke baghair mileage nahi nikalti.']),

('milk-collection.generator','rm',
 'Generator ka hisaab: kitna chala aur kitna tel laga.',
 'Doodh ka staff.',
 'Har dafa chalne par.',
 array['Ghante aur tel likhein.'],
 'Ye kharcha bhi fi litre mein jata hai.',
 array['Sirf tel likhna kaafi nahi -- ghante bhi likhein, warna kharcha samajh nahi aata.']),

('milk-collection.maintenance','rm',
 'Gaari aur marammat: kis gaari par kya kharch hua.',
 'Fleet aur doodh ka staff.',
 'Har marammat par.',
 array['Gaari chunein.','Kaam aur raqam likhein.','Raseed lagayein.'],
 'Baar baar wahi marammat ho to gaari badalne ka faisla.',
 array['Chhoti marammat darj na karna poore kharche ko chhupa deta hai.']),

('drivers','rm',
 'Driver aur gaariyan: kaun si gaari kis ke paas hai.',
 'Fleet aur Admin.',
 'Naya driver ya gaari aane par.',
 array['Driver aur gaari jorein.','License aur kaghazat likhein.'],
 'Roz ka istemal Gaariyan ke safhe par.',
 array['License ki miyaad khatam hona ek bara khatra hai -- tareekh likhein.']),

('vehicles','rm',
 'Gaariyan (rozana): roz ka meter, tel aur kaam.',
 'Driver aur fleet.',
 'Roz.',
 array['Gaari chunein.','Meter aur tel likhein.','Kaam ki tafseel likhein.'],
 'Mahine ke aakhir mein kharche ka jaiza.',
 array['Meter ghalat likhne se mileage ka poora hisaab bekar ho jata hai.']),

('my-vehicle','rm',
 'Meri gaari: apni gaari ka roz ka record.',
 'Driver.',
 'Roz, kaam shuru aur khatam par.',
 array['Meter likhein.','Tel daala ho to us ki raseed lagayein.'],
 'Manager isi record se kharcha dekhta hai.',
 array['Baad mein yaad se likhna aksar ghalat hota hai -- usi waqt likhein.']),

('field-watch','rm',
 'Maidan ki nigrani: bahar kaam karne walon ki halat.',
 'Manager aur Owner.',
 'Roz.',
 array['Fehrist kholein.','Kaun kahan hai aur kya kar raha hai, dekhein.'],
 'Koi cheez ruki lage to us ke safhe par jayein.',
 array['Ye nigrani kaam ke liye hai, shak ke liye nahi -- adad se pehle banday se baat karein.']),

('trust_intelligence','rm',
 'Bharosa aur karkardagi: kis ka kaam kaisa chal raha hai.',
 'Owner aur Admin.',
 'Mahine mein ek dafa.',
 array['Banda ya shaakh chunein.','Us ka score aur us ki wajah dekhein.'],
 'Score kam ho to us ki wajah par baat karein.',
 array['Score ko saza banane se log adad theek karne lagte hain, kaam nahi -- ye us ka maqsad nahi.'])

on conflict (feature_key, lang) do update set
  purpose = excluded.purpose, who_uses = excluded.who_uses, when_use = excluded.when_use,
  how_steps = excluded.how_steps, next_step = excluded.next_step, mistakes = excluded.mistakes,
  updated_at = now();
