-- =====================================================================
-- AgriBridge — Migration 286: Anaj, Reports aur amali safhon ka help
-- =====================================================================
-- Teen guchhe:
--   1. Anaj (kharid, dashboard, adaigi, bechna, khata, godam) -- 6
--   2. Reports (finance, sale, kharid, udhaar, doodh, anaj, nafa
--      nuqsan, audit center) -- 9
--   3. Amali safhe: supplier statement, POS wapsi, adhoore products,
--      rate master, machinery se aayi grain leads, AI ki kharid
--      tajweez, AI ki hidayaat, Bridge AI ke action requests aur
--      activity log, karobar/master/website dashboard, dashboard
--      manager, test data reset, platform aur subscriptions -- 16
--
-- Reports par ek baat baar baar likhi gayi hai: koi report apna alag
-- hisaab nahi rakhti. Wo wohi record kholti hai jo pehle se maujood
-- hai. Do reportein alag adad dikhayein to arsa ya bunyaad alag hai --
-- hisaab nahi.
-- =====================================================================

insert into feature_help (feature_key, lang, purpose, who_uses, when_use, how_steps, next_step, mistakes) values
('grain-procurement','rm',
 'Anaj ki kharid: kisan ya party se anaj lena aur us ka bill banana.',
 'Anaj ka staff aur manager.',
 'Jab anaj aaye -- usi waqt.',
 array['Bechne wala chunein: kisan ya party.','Anaj ki qisam, wazan aur rate likhein.','Kaat (cut) chunein -- namee ya safai ki -- preset se khud lag jati hai.','Godam chunein jahan anaj rakha ja raha hai.','Entry mehfooz karein.'],
 'Adaigi Kisan ki Adaigi ke safhe par hoti hai, yahan nahi.',
 array['Anaj lena subah ka kaam hai aur adaigi shaam ka -- dono ko ek sath karne ki koshish mein aksar ghalat raqam nikal jati hai.','Kaat ka percentage haath se badalne se pehle wajah likhein -- yehi kisan ke sath sab se bara jhagRa hai.']),

('grain-procurement.dashboard','rm',
 'Anaj ka dashboard: kitna anaj aaya, kitna bika aur kitna nafa hua.',
 'Anaj ka manager aur Owner/Admin.',
 'Roz, aur season ke dauran har hafte.',
 array['Kharid, bikri aur kharche ke adad dekhein.','Kisi adad par click kar ke us ki asal fehrist kholein.'],
 'Godam ka wazan Anaj ka Godam par milta hai.',
 array['Nafa tab tak adhoora hai jab tak sab kharche (mazdoori, bardana, safai) darj na hon.']),

('grain-procurement.payments','rm',
 'Kisan ki adaigi: kis ka kitna baqi hai aur us ko kitna diya ja raha hai.',
 'Anaj ka staff aur finance.',
 'Shaam ko, ya jab kisan paisa lene aaye.',
 array['Fehrist kholein -- sab se bara baqi pehle.','Kisan ya party chunein.','Raqam, khata aur tareekh likh kar adaigi darj karein.'],
 'Adaigi cash book aur us ke khate dono mein khud chali jati hai.',
 array['Adaigi karte waqt saamne sirf ye hona chahiye ke kis ka kitna baqi hai -- nayi entry usi waqt na banayein.','Ek adaigi do dafa darj karna sab se aam ghalti hai; pehle fehrist mein dekh lein.']),

('grain-procurement.sell','rm',
 'Anaj bechna: godam se anaj kharidar ko bechna.',
 'Anaj ka manager.',
 'Jab sauda ho.',
 array['Kharidar chunein.','Godam, anaj ki qisam, wazan aur rate likhein.','Milne wali raqam darj karein.','Bikri mehfooz karein.'],
 'Bikri ke baad godam ka wazan khud kam ho jata hai.',
 array['Godam mein jitna anaj hai us se zyada bechna nahi chahiye -- pehle godam dekh lein.','Lagat (COGS) khud nikalti hai; usay haath se na likhein.']),

('grain-procurement.statement','rm',
 'Anaj ka khata: ek bechne wale ki poori kahani -- kitna anaj diya, kitna paisa liya.',
 'Anaj ka staff, finance aur manager.',
 'Jab kisan ya party hisaab poochein.',
 array['Kisan ya party chunein.','Us ki har entry aur har adaigi tarteeb se dekhein.','Zaroorat ho to print ya WhatsApp karein.'],
 'Baqi raqam Kisan ki Adaigi par ada hoti hai.',
 array['Khata haath se theek nahi hota -- ghalti entry mein hoti hai, us ko theek karein.']),

('grain-procurement.warehouse','rm',
 'Anaj ka godam: kaunsa anaj kitna para hai aur us mein kitna paisa phansa hai.',
 'Anaj ka manager aur Owner/Admin.',
 'Har subah, aur bechne se pehle.',
 array['Godam chunein.','Har anaj ka wazan aur us ki lagat dekhein.'],
 'Bechna ho to Grain Bechein par jayein.',
 array['Ye wazan khud nahi likha jata -- entries se aata hai aur bikri se jata hai. Farq lage to ginti karwayein, adad na badlein.']),

('reports','rm',
 'Reports: poore karobar ki reportein ek jagah.',
 'Owner, Admin aur manager.',
 'Hafte mein ek dafa, aur mahine ke aakhir mein.',
 array['Report chunein.','Arsa aur shaakh chunein.','Adad par click kar ke asal qatarein kholein.'],
 'Kisi qatar par kaam ho to usi safhe par ja kar qadam poora karein.',
 array['Koi report apna alag hisaab nahi rakhti -- wo wohi record kholti hai jo pehle se hai. Do reportein alag adad dein to arsa ya bunyaad alag hai.']),

('reports.finance','rm',
 'Finance report: poori company ka cash book -- aamdani, kharcha aur khaton ka balance.',
 'Owner, Admin aur finance.',
 'Mahine ke aakhir mein, aur jab paise ka jaiza lena ho.',
 array['Arsa chunein.','Aamdani aur kharche ki qismein dekhein.','Har khate ka balance dekhein.'],
 'Farq lage to Roz ka Milaan aur Bank Milaan se jaanchein.',
 array['Yahan ke adad entries se bante hain -- balance haath se theek karne ki koshish na karein.']),

('reports.sales','rm',
 'Sale report: sab shaakhon aur dealers ki bikri.',
 'Owner, Admin, manager aur sales.',
 'Roz shaam, aur mahine ke aakhir mein.',
 array['Arsa aur shaakh chunein.','Bikri, cashier aur qisam ke hisaab se dekhein.'],
 'Kisi bill par shak ho to POS ka record kholein.',
 array['Wapsi (returns) bikri se alag hoti hai -- dono ko mila kar na parhein.']),

('reports.purchases','rm',
 'Kharid report: sab shaakhon ke purchase order.',
 'Owner, Admin, manager aur purchase ka staff.',
 'Har hafte.',
 array['Arsa aur shaakh chunein.','Supplier aur cheez ke hisaab se kharid dekhein.'],
 'Kisi kharid par sawal ho to us ka purchase kholein.',
 array['Order dena aur maal aana do alag cheezein hain -- order ki raqam ko maal ki raqam na samjhein.']),

('reports.credit','rm',
 'Udhaar report: kisanon ko kitna udhaar diya, kitna wapas aaya aur kitna baqi hai.',
 'Owner, Admin aur finance.',
 'Har hafte.',
 array['Arsa chunein.','Diya gaya, wapas aaya aur baqi -- teen adad alag alag dekhein.','Sab se bare baqi wale kisanon ko dekhein.'],
 'Wusooli ke liye us kisan ke khate par jayein.',
 array['Baqi zyada hona hamesha khatra nahi -- season ke hisaab se dekhein.']),

('reports.milk','rm',
 'Doodh report: collection, rate aur kisanon ka baqi.',
 'Doodh ka manager aur finance.',
 'Roz, aur bill ke waqt.',
 array['Arsa chunein.','Litre, FAT aur rate dekhein.','Kisanon ka baqi dekhein.'],
 'Adaigi doodh ke apne safhe se hoti hai.',
 array['Jama kiya hua aur tasdeeq shuda doodh ek nahi -- report parhte waqt ye farq yaad rakhein.']),

('reports.procurement','rm',
 'Anaj kharid report: fasal ke hisaab se kharid aur kisanon ka baqi.',
 'Anaj ka manager aur Owner/Admin.',
 'Season ke dauran har hafte.',
 array['Arsa chunein.','Har fasal ka wazan aur raqam dekhein.','Kisanon ka baqi dekhein.'],
 'Baqi ada karna ho to Kisan ki Adaigi par jayein.',
 array['Kaat ke baad wala wazan aur asal wazan alag hote hain -- report parhte waqt ye farq dekhein.']),

('reports.pnl','rm',
 'Nafa nuqsan (shop-wise): kis dukan ne kitna kamaya aur kis cheez par.',
 'Owner aur Admin.',
 'Mahine ke aakhir mein.',
 array['Shaakh ya dukan chunein.','Har cheez ka nafa dekhein.','Kharche ka hissa dekhein.'],
 'Nuqsan wali cheez ka rate ya lagat dekhein.',
 array['Company ke wo kharche jo abhi manzoor nahi hue, is hisaab mein nahi aate.']),

('reports.audit','rm',
 'Audit center (nuqsan): stock ka nuqsan, farq aur us ki tasdeeq.',
 'Owner, Admin aur wo staff jo verifier bana ho.',
 'Har hafte, aur ginti ke baad.',
 array['Dukan chunein.','Nuqsan ki qatarein dekhein: kya, kitna aur kis ne likha.','Har qatar par tasdeeq karein ya sawal karein.'],
 'Bara nuqsan ho to us ki tehqeeq Audit Trail se karein.',
 array['Nuqsan likhna saza nahi -- chhupaya gaya nuqsan hamesha bara nikalta hai.','Verifier wohi ho jo us dukan par khud kaam na karta ho.']),

('suppliers.all-statement','rm',
 'Sab suppliers ka statement: kis supplier ka kitna bill hai aur kitna ada hua.',
 'Finance aur purchase ka staff.',
 'Mahine ke aakhir mein, aur adaigi se pehle.',
 array['Arsa chunein.','Har supplier ka bill, adaigi aur baqi dekhein.','Kisi supplier par click kar ke us ki tafseel kholein.'],
 'Adaigi karni ho to us ka apna safha kholein.',
 array['Bill aur adaigi ki tareekhein alag hoti hain -- baqi dekhte waqt arsa dhyan se chunein.']),

('pos.returns','rm',
 'POS wapsi: gahak se wapas aayi hui cheez.',
 'Dukan ka staff -- manager ka code lagta hai.',
 'Jab gahak cheez wapas laye.',
 array['Asal bill dhoondein.','Wapas aane wali cheez aur miqdar chunein.','Manager ka code daalein.','Wapsi mehfooz karein.'],
 'Cheez wapas stock mein aa jati hai aur raqam gahak ko wapas hoti hai.',
 array['Wapsi ki fehrist sab ko nazar aati hai, sirf manager ko nahi -- ye jaan boojh kar hai, taake ghalat naam par lagi wapsi pakRi ja sake.','Bina bill ke wapsi na lein.']),

('products.setup_queue','rm',
 'Adhoore products: jin cheezon ka rate, barcode, tasveer, miyaad ya manzoori baqi hai.',
 'Product manager aur Admin.',
 'Roz, aur nayi cheezein daalne ke baad.',
 array['Fehrist kholein -- upar ginti, neeche wo cheezein jin ka kaam baqi hai.','Har cheez ka khali khana bharein.','Mehfooz karein.'],
 'Poori cheez POS aur order par khud aane lagti hai.',
 array['Rate ke baghair cheez POS par nahi bik sakti -- log samajhte hain stock khatam hai.']),

('rate-master','rm',
 'Rate master: zameen ki tayari aur mazdoori ke rate.',
 'Owner, Admin aur manager.',
 'Season se pehle, aur rate badalne par.',
 array['Kaam ki qisam chunein.','Fi acre ya fi mazdoor rate likhein.','Mehfooz karein.'],
 'Kisan ke kharche ke form mein ye rate khud aa jate hain.',
 array['Purane rate season badalne par theek karna na bhoolein -- warna kisan ko purana adad nazar aata hai.']),

('grain.machinery-leads','rm',
 'Machinery se grain leads: jin kisanon ne kattai ke waqt kaha ke fasal hamein bechenge.',
 'Anaj ka staff.',
 'Kattai ke season mein roz.',
 array['Fehrist kholein.','Kisan se raabta karein aur rate ki baat karein.','Sauda ho to Anaj ki Kharid par entry banayein.'],
 'Asal kharid Anaj ki Kharid par darj hoti hai.',
 array['Ye sirf KHABAR hai, SAUDA nahi. Haan keh dene ko kharid bana kar likhna teen jhoot ek sath likhta hai: rate jo tay nahi hua, wazan jo hua nahi, aur maal jo aaya nahi -- aur wo teenon godam aur nafa nuqsan dono mein ja baithte hain.']),

('ai-suggestions','rm',
 'AI ki kharid tajweez: AI batata hai kaun si cheez khatam hone wali hai aur kitni mangwani chahiye.',
 'Purchase ka staff aur manager.',
 'Roz, order dene se pehle.',
 array['Tajweez ki fehrist kholein.','Har tajweez ki wajah dekhein: kitna stock hai aur kitna bik raha hai.','Theek lage to us se purchase order banayein; na lage to chhoR dein.'],
 'Order Kharid ke safhe par banta hai.',
 array['AI sirf tajweez deta hai, order khud nahi banata -- faisla insaan ka hai.','Bina stock dekhe tajweez par order de dena godam bhar deta hai.']),

('ai-instructions','rm',
 'AI ki hidayaat: AI ko batayein ke report banate waqt kis baat ka khayal rakhe.',
 'Owner aur Admin.',
 'Jab AI ki report ka andaz badalna ho.',
 array['Hidayat likhein (saada zaban mein).','Mehfooz karein.'],
 'Har roz ki report ab in hidayaat ke mutabiq banti hai.',
 array['Hidayat mein adad ya qanoon na likhein -- wo code se aate hain. Yahan sirf andaz aur tawajjah likhein.']),

('bridge-ai.action-requests','rm',
 'Bridge AI ke action requests: jo kaam AI ne tajweez kiya aur insaan ki manzoori ka muntazir hai.',
 'Owner, Admin aur manager.',
 'Roz.',
 array['Qatar kholein.','Har tajweez ki tafseel dekhein: kya cheez, kitni miqdar, kis rate par.','Supplier, shaakh, miqdar aur rate darust karein.','Manzoor karein, wajah ke sath wapas bhejein, ya radd karein.'],
 'Manzoori ke baad us ka purchase ya order khud ban jata hai.',
 array['AI khud kabhi record nahi banata -- sirf tajweez deta hai. Bina parhe manzoori aap ke naam par likhi jati hai.']),

('bridge-ai.activity-log','rm',
 'Bridge AI ka activity log: AI ne kya poocha gaya aur kya jawab diya.',
 'Owner aur Admin.',
 'Jab dekhna ho ke AI kya kar raha hai.',
 array['Log kholein.','Arsa ya banda chunein.','Qatarein parhein.'],
 'Koi jawab ghalat lage to AI ki Hidayaat par hidayat theek karein.',
 array['Ye log mitaya nahi ja sakta -- yehi is ka faida hai.']),

('business-dashboard','rm',
 'Karobar ka dashboard: shaakhon ki bikri, khate aur roz ka khulasa.',
 'Owner, Admin aur manager.',
 'Roz subah aur shaam.',
 array['Shaakh chunein ya sab dekhein.','Aaj ki bikri aur khaton ke adad dekhein.','Kisi adad par click kar ke us ki asal fehrist kholein.'],
 'Kaam wali cheez ho to us ke apne safhe par jayein.',
 array['Yahan ke adad khud nahi likhe jate -- records se bante hain.']),

('command-center','rm',
 'Malik ka command center: aaj ka paisa, har department ki halat aur wo cheezein jin par foran nazar chahiye.',
 'Owner (aur Admin).',
 'Roz subah.',
 array['Aaj ka paisa dekhein.','Har department ka adad dekhein.','Alert wale hisse mein har qatar par faisla karein.'],
 'Har alert seedha us safhe par le jata hai jahan qadam poora hota hai.',
 array['Alert ko dekh kar chhoR dena is safhe ko bekar kar deta hai -- yahi wo jagah hai jahan se rukka hua kaam chalta hai.']),

('master-dashboard','rm',
 'Master dashboard: bank, stock aur shaakhon ka udhaar -- poore karobar ki ek tasveer.',
 'Owner aur Admin.',
 'Roz ek dafa.',
 array['Bank ke balance dekhein.','Stock ki qeemat dekhein.','Shaakhon ka udhaar dekhein.'],
 'Kisi hisse ki tafseel us ke apne safhe par.',
 array['Stock ki qeemat kharid ke rate par hai, bikri ke rate par nahi -- dono ka farq yaad rakhein.']),

('dashboard','rm',
 'Website dashboard: website se aane wali darkhwastein aur karobar ka khulasa.',
 'Admin aur sales.',
 'Roz.',
 array['Nayi darkhwastein dekhein.','Chart se rujhaan dekhein.','Kisi qatar par click kar ke us ka safha kholein.'],
 'Kaam wali darkhwast ho to us par jawab dein.',
 array['Website ki darkhwast lead hai, sauda nahi -- us ko order na samjhein.']),

('dashboard-manager','rm',
 'Dashboard aur feature manager: kis role ko kaun se safhe aur kaun se kaam khulte hain.',
 'Owner aur super admin.',
 'Shuru mein, aur jab kisi role ka kaam badle.',
 array['Role chunein.','Har feature ke saamne kaam chunein (dekhna, banana, manzoor karna...).','Data ka daira chunein.','Mehfooz karein.'],
 'Ek bande ki alag ijazat Ijazat ke safhe se di jati hai.',
 array['Role ki ijazat badalna us role ke HAR bande par lagta hai -- ek bande ke liye role na badlein.','Bara ikhtiyar dene se pehle takraao (SoD) ki jaanch dekh lein.']),

('reset-test-data','rm',
 'Test data reset: testing ke dauran daala gaya data saaf karna.',
 'Owner aur super admin -- sirf testing par.',
 'Jab testing ka data saaf karna ho.',
 array['Safha kholein aur tanbeeh parhein.','Jo hissa saaf karna hai wo chunein.','Tasdeeq karein.'],
 'Products, staff, shaakhein/dukanein, website ka content aur settings hamesha bache rehte hain.',
 array['Ye raasta Live par band hai (is_live ka taala) -- aur yehi is ka sab se ahem hissa hai.','Reset se pehle yaqeen kar lein ke aap testing par hain, Live par nahi.']),

('platform','rm',
 'Platform / clients: wo idare jo AgriBridge istemal kar rahe hain.',
 'Super admin.',
 'Naya client aane par.',
 array['Idara jorein ya chunein.','Us ki maloomat aur halat dekhein.'],
 'Har idare ka apna data alag rehta hai.',
 array['Ek idare ka data doosre ke saath na milayein.']),

('subscriptions','rm',
 'Subscriptions: kisanon ki subscription aur elaanaat.',
 'Admin aur sales.',
 'Naya plan banne par, ya elaan bhejte waqt.',
 array['Plan ki settings dekhein.','Kisan ki subscription chunein ya banayein.','Elaan banayein aur bhejein.'],
 'Elaan kisanon ko un ke apne safhe par nazar aata hai.',
 array['Elaan bhejne se pehle ginti dekh lein -- kitne logon tak ja raha hai.'])

on conflict (feature_key, lang) do update set
  purpose = excluded.purpose, who_uses = excluded.who_uses, when_use = excluded.when_use,
  how_steps = excluded.how_steps, next_step = excluded.next_step, mistakes = excluded.mistakes,
  updated_at = now();
